### PR TITLE
loggamma

### LINKED ISSUE #1528: loggamma
`SpecialFunctions.lgamma` is depcrecated in favor of `SpecialFunctions.loggamma`

https://github.com/JuliaGPU/CUDA.jl/blob/f68879ac391b10da1ef9df3a4257eb68a76f1d5e/src/device/intrinsics/special_math.jl#L24

We should update the name here.

### PR DESCRIPTION
**Pull request by cossio**
Closes #1528

### CODE REVIEW

**Comment by vchuravy** [comment]
We will need to support both versions in case someone is using the older version. Maybe a `isdefined` check on `loggamma`?

**Comment by cossio** [comment]
@vchuravy `lgamma` was deprecated 3 years ago in SpecialFunctions v0.8 (https://github.com/JuliaMath/SpecialFunctions.jl/releases/tag/v0.8.0), which CUDA doesn't support. The current compat lower bound is 1.3

https://github.com/JuliaGPU/CUDA.jl/blob/f68879ac391b10da1ef9df3a4257eb68a76f1d5e/Project.toml#L42

Do you still think we would need that check?

**Comment by maleadt** [comment]
I don't think we do. Could you add a test though?

**Comment by cossio** [comment]
@maleadt Test added.

Can we tag a release with this? If so, should I bump the version number here?

**Comment by maleadt** [comment]
CI is running already now, I'll bump the version after merging.

**Comment by cossio** [comment]
Test passed. Ready to merge?

**Pull request merged**
