### PR TITLE
do not open the file twice when reading the libdevice bitcode

### PR DESCRIPTION
**Pull request by jakebolewski**
Might help with #293 with the shared pvfs (GPFS) we are using on the cluster.

### CODE REVIEW

**Review by vchuravy — APPROVED** [review]
Good observation!

**Comment by maleadt** [comment]
Thanks!
bors r+

**Comment by jakebolewski** [comment]
@maleadt would it be possible to tag a new version after this is merged so we can see if it fixes the issue?

**Comment by maleadt** [comment]
https://github.com/JuliaRegistries/General/pull/17959

**Pull request merged**
