### PR TITLE
Backport Enzyme extension

### PR DESCRIPTION
**Pull request by wsmoses**
@maleadt lmk if this is good.

I'll probably be working on some more stuff that will be helpful to backport later as well, but this already should hopefully unblock KA

### CODE REVIEW

**Comment by maleadt** [comment]
Tests fail.

**Review by maleadt — CHANGES_REQUESTED** [review]
Tests fail.

**Comment by wsmoses** [comment]
@maleadt this now looks to be passing (though the other errors seem unrelated)?

**Comment by maleadt** [comment]
LGTM.

**Pull request merged**
