### PR TITLE
Fix accumulate bug

### LINKED ISSUE #1810: accumulate(+) gives different results for CuArray compared to Array.
**Describe the bug**

The results I am getting on my machine for accumulate(+) when dims = 1 on a CuArray are different from the results on an Array.  

The issue arises with certain array sizes.  The array size must be greater than (1024, 1) - in both dimensions - however, it then returns the correct values whenever the number of rows is equal to a multiple of 1024.  Only the array cells in the columns with an index greater or equal to 'floor(size(<gpu_array>)[2] / 2)' are incorrect, or in other words parts of the lower right quadrant of the array.  An example is included in the MWE for clarification.

**To reproduce**

The Minimal Working Example (MWE) for this bug:

```julia
using CUDA

function resultsmatch(rows::Int64, cols::Int64)
  arr_gpu = CUDA.ones(rows, cols)
  all(Array(accumulate(+, arr_gpu, dims = 1)) .== accumulate(+, Array(arr_gpu), dims = 1))
end

resultsmatch(1024 * 1 - 1, 2) # true
resultsmatch(1024 * 1 + 0, 2) # true
resultsmatch(1024 * 1 + 0, 5) # true

resultsmatch(1024 * 1 + 1, 2) # false
resultsmatch(1024 * 2 - 1, 2) # false
resultsmatch(1024 * 2 + 0, 2) # true
resultsmatch(1024 * 2 + 1, 2) # false

resultsmatch(1024 * 2 - 1, 5) # false
resultsmatch(1024 * 2 + 0, 5) # true
resultsmatch(1024 * 2 + 1, 5) # false

resultsmatch(1024 * 5 - 1, 5) # false
resultsmatch(1024 * 5 + 0, 5) # true
resultsmatch(1024 * 5 + 1, 5) # false

# Example of results:
accumulate(+, CUDA.ones(1027, 5), dims = 1)
#1027×5 CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}:
#    1.0     1.0     1.0     1.0     1.0
#    2.0     2.0     2.0     2.0     2.0
#    3.0     3.0     3.0     3.0     3.0
#    ⋮                            
# 1024.0  1024.0  1024.0  1024.0  1024.0
# 1025.0  1025.0  1025.0     1.0     1.0
# 1026.0  1026.0  1026.0     2.0     2.0
# 1027.0  1027.0  1027.0     3.0     3.0
```

<details><summary>Manifest.toml</summary>
<p>

```
julia_version = "1.8.0"
manifest_format = "2.0"

...

[[deps.CUDA]]
deps = ["AbstractFFTs", "Adapt", "BFloat16s", "CEnum", "CUDA_Driver_jll", "CUDA_Runtime_Discovery", "CUDA_Runtime_jll", "CompilerSupportLibraries_jll", "ExprTools", "GPUArrays", "GPUCompiler", "LLVM", "LazyArtifacts", "Libdl", "LinearAlgebra", "Logging", "Preferences", "Printf", "Random", "Random123", "RandomNumbers", "Reexport", "Requires", "SparseArrays", "SpecialFunctions"]
git-tree-sha1 = "edff14c60784c8f7191a62a23b15a421185bc8a8"
uuid = "052768ef-5323-5732-b1bb-66c8b64840ba"
version = "4.0.1"

[[deps.CUDA_Driver_jll]]
deps = ["Artifacts", "JLLWrappers", "LazyArtifacts", "Libdl", "Pkg"]
git-tree-sha1 = "75d7896d1ec079ef10d3aee8f3668c11354c03a1"
uuid = "4ee394cb-3365-5eb0-8335-949819d2adfc"
version = "0.2.0+0"

[[deps.CUDA_Runtime_Discovery]]
deps = ["Libdl"]
git-tree-sha1 = "58dd8ec29f54f08c04b052d2c2fa6760b4f4b3a4"
uuid = "1af6417a-86b4-443c-805f-a4643ffb695f"
version = "0.1.1"

[[deps.CUDA_Runtime_jll]]
deps = ["Artifacts", "CUDA_Driver_jll", "JLLWrappers", "LazyArtifacts", "Libdl", "Pkg", "TOML"]
git-tree-sha1 = "d3e6ccd30f84936c1a3a53d622d85d7d3f9b9486"
uuid = "76a88914-d11a-5bdc-97e0-2f5a05c973a2"
version = "0.2.3+2"

...

[[deps.GPUArrays]]
deps = ["Adapt", "GPUArraysCore", "LLVM", "LinearAlgebra", "Printf", "Random", "Reexport", "Serialization", "Statistics"]
git-tree-sha1 = "a28f752ffab0ccd6660fc7af5ad1c9ad176f45f7"
uuid = "0c68f7d7-f131-5f86-a1c3-88cf8149b2d7"
version = "8.6.3"

[[deps.GPUArraysCore]]
deps = ["Adapt"]
git-tree-sha1 = "1cd7f0af1aa58abc02ea1d872953a97359cb87fa"
uuid = "46192b85-c4d5-4398-a991-12ede77f4527"
version = "0.1.4"

[[deps.GPUCompiler]]
deps = ["ExprTools", "InteractiveUtils", "LLVM", "Libdl", "Logging", "TimerOutputs", "UUIDs"]
git-tree-sha1 = "95185985a5d2388c6d0fedb06181ad4ddd40e0cb"
uuid = "61eb1bfa-7361-4325-ad38-22787b887f55"
version = "0.17.2"

...

[[deps.LLVM]]
deps = ["CEnum", "LLVMExtra_jll", "Libdl", "Printf", "Unicode"]
git-tree-sha1 = "df115c31f5c163697eede495918d8e85045c8f04"
uuid = "929cbde3-209d-540e-8aea-75f648917ca0"
version = "4.16.0"

[[deps.LLVMExtra_jll]]
deps = ["Artifacts", "JLLWrappers", "LazyArtifacts", "Libdl", "Pkg", "TOML"]
git-tree-sha1 = "7718cf44439c676bc0ec66a87099f41015a522d6"
uuid = "dad2f222-ce93-54a1-a47d-0025e8a3acab"
version = "0.0.16+2"

...

```

</p>
</details>

**Expected behavior**

The results for accumulate(+) when run on CuArray and Array match.

**Version info**

Details on Julia:

```
Julia Version 1.8.0
Commit 5544a0fab76 (2022-08-17 13:38 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 12 × Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 4 on 12 virtual cores
Environment:
  JULIA_NUM_THREADS = 4
  JULIA_EDITOR = code
```

Details on CUDA:

```
CUDA runtime 11.8, artifact installation
CUDA driver 11.4
NVIDIA driver 470.161.3

Libraries: 
- CUBLAS: 11.11.3
- CURAND: 10.3.0
- CUFFT: 10.9.0
- CUSOLVER: 11.4.1
- CUSPARSE: 11.7.5
- CUPTI: 18.0.0
- NVML: 11.0.0+470.161.3

Toolchain:
- Julia: 1.8.0
- LLVM: 13.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0, 7.1, 7.2
- Device capability support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80, sm_86

1 device:
  0: NVIDIA GeForce GTX 1660 Ti (sm_75, 4.918 GiB / 5.805 GiB available)
```

### PR DESCRIPTION
**Pull request by chrstphrbrns**
Fixes #1810

Tested using the test cases given in the issue

### CODE REVIEW

**Comment by maleadt** [comment]
Rebased. Looks like the CI failures here are related.

**Comment by chrstphrbrns** [comment]
The only error I'm able to repro locally is `LLVM error: Symbol name with unsupported characters`, which seems unlikely to be related to the changes made in this PR. The `reducedim!` and `cusparse/reduce` tests pass for me

**Comment by maleadt** [comment]
> The only error I'm able to repro locally is `LLVM error: Symbol name with unsupported characters`

You're using Julia 1.11 then, which is unsupported.

Did you try Julia 1.7? That's, according to CI, the only version where this issue occurs.
I'm going to drop support for 1.7 soon though, so probably not worth looking into.

**Comment by maleadt** [comment]
Thanks!

**Pull request merged**
