### PR TITLE
Backports for 3.12.1

### PR DESCRIPTION
**Pull request by maleadt**
Since the next release is breaking (v4.0), I'm happy to do a patch release to backport crucial fixes. So if anybody wants anything in (no large features, of course), please let me know here in the next few days.

### CODE REVIEW

**Comment by amontoison** [comment]
Is it possible to backport the recent modifications and fixes of CUSPARSE?

**Comment by maleadt** [comment]
> Is it possible to backport the recent modifications and fixes of CUSPARSE?

No, those are much too invasive, and add features. I just intend this to be a release for people who can't yet upgrade to the breaking release of CUDA v4.0, which I also intend to release soon.

**Comment by maleadt** [comment]
Pushed some more fixes; if we're doing a backport we could as well make it better. This also fixed 1.9 compatibility.

**Comment by maleadt** [comment]
I'll merge and tag this already; even though 1.9-beta3 isn't ready yet I don't expect it to break CUDA.jl again. Meanwhile, this PR contains some actual fixes (like CUDA 12 support), so would be good to get out there.

**Pull request merged**
