### PR TITLE
[CUSOLVER] Improve the dispatch for LAPACK routines

### PR DESCRIPTION
**Pull request by amontoison**

### CODE REVIEW

**Comment by maleadt** [comment]
Is the `chkuplo` check not relevant? Base is still doing it in its LAPACK wrappers.

**Comment by amontoison** [comment]
`chkuplo` is relevant but we need Julia 1.8 or higher to use it.

**Comment by maleadt** [comment]
Wouldn't it be better to do a `VERSION >= v"1.8" && chkuplo` then, or isn't it worth it?

**Comment by amontoison** [comment]
I think it's better to do a `VERSION >= v"1.8" && chkuplo(uplo)`.

**Pull request merged**
