### PR TITLE
Unified CuArray type

### PR DESCRIPTION
**Pull request by akashkgarg**
This is a convenience class that allows for safe memory tracking for arrays that live on the unified memory. Currently one must manually allocate/free and convert to CuArray. The goal for this type is to work seamlessly in a multi-gpu environment where all CuUnifiedArrays can be accessed by available devices. There seems to be a related issue to this here: #28 . 

Please note that is very much a work in progress but I am opening a draft PR here to gather feedback/comments/criticisms from those more familiar with best practices.

### CODE REVIEW

**Comment by maleadt** [comment]
Why a separate array type, and not just re-use CuArray? It just contains a CuPtr, after all. A method could be provided to `unsafe_convert` a unified CuArray to an Array then.

**Comment by akashkgarg** [comment]
@maleadt Thanks for the suggestion. That's what I originally was thinking about: making a new ArrayState something like `ARRAY_UNIFIED` and then checking for that state in `unsafe_finalizer!` to free the memory properly. Since I'm not an expert on this, I was timid in going down that road to avoid inadvertently breaking something in `CuArray`; but I can take a stab at that if you think that is the correct approach.

**Comment by maleadt** [comment]
I think it might be easier, because you don't have to duplicate the array interface. The disadvantage is that derived Arrays aren't tied to their CuArray (so might live past the allocation's lifetime), whereas otherwise the CuUnifiedArray could support both CPU and GPU operations.

A separate ArrayState sounds like a good way to implement this.

**Comment by akashkgarg** [comment]
Actually thinking more about this, I think another reason for creating another concrete type for `CuUnifiedArray` was to support composition in other packages that use things like `adapt`. For example, packages like DiffEq use `adapt` to create compatible array types to seamlessly support operations on CPU/GPU depending on the array type. I would like to support this for Multi-GPU environment such that `adapt` will return UnifiedArrays that live in unified memory and work can be distributed across multiple gpus. Maybe instead of another concrete type, I should add another type parameter to CuArray, something like 
```julia
@enum MemType Device Unified
mutable struct CuArray{T,N,MemType}
...
end
```

**Comment by akashkgarg** [comment]
I'm running into a bit of an issue with `reshape` on unified arrays. I see that CuArray's have their own reshape function that essentially increments the ref-count in a custom memory allocator; which makes sense since ownership has increased one on the returned reshaped array and one on the original array. I'm wondering if we need to do something similar with UnifiedArrays, e.g., make an allocator pool for unified arrays to keep track of ref counts? Is there another way around this? It seems to me that we can't use CuArray allocator pool for Unified Arrays since the alloc/free semantics are slightly different than normal CuArrays?

**Comment by maleadt** [comment]
Correct. But what that refcounting part of the CUDA.jl allocator essentially does, is map a CuPtr to a Block containing a DeviceBuffer. We could generalize that to make it contain any kind of buffer. It used to be like that in the past, but it resulted in type-unstable code (although maybe a `Union{DeviceBuffer,UnifiedBuffer}` would work).

Longer term, I plan on removing the pools, which would get rid of a lot of complexity (e.g. the Block would go, and CuPtrs would directly map on buffers).

**Comment by maleadt** [comment]
As you may have seen, based on the discussion here I did some redesign of the array type to facilitate using different storage types. Based on that, https://github.com/JuliaGPU/CUDA.jl/pull/1023 extends the CuArray type with unified memory support. Let me know what you think!

**Comment by akashkgarg** [comment]
#1023 looks great and far simpler than my approach here. However I do see one limitation with converting between types. Consider the following:
```julia
a = CuArray{Float32}(undef, Dims((10,)), unified=true)
is_managed(pointer(a)) # returns true
b = Adapt.adapt(DiffEqBase.parameterless_type(a), rand(10))
is_managed(pointer(b)) # returns false
```
In the above, I think we want `b` to be a unified array as well and is the primary reason why I had opted for creating a new type so that conversions can be dispatched on the type appropriately. Maybe there's another way to write adapt to handle this case?

**Comment by maleadt** [comment]
Yeah, I don't know. It seems excessive to make this a type parameter, or worse a different type, because there's almost no difference in behavior (at least not wrt. method dispatch): both kinds of arrays can be converted to a device pointer, so the same kinds of operations work on both.

**Comment by akashkgarg** [comment]
I think the main motivation here is to have multi-gpu support seamlessly with existing codes. One concrete use-case is doing ML type operations on the GPU. Right now one can create a neural-network like so: `Chain(Dense(...), Dense(...)) |> gpu` and things will work as expected on GPU vs CPU. I was hoping we can do something similar with `Chain(Dense(...), Dense(...)) |> multigpu` and all operations from there on would work across multiple GPUs. Maybe that's a lofty goal and perhaps applications that require multi-gpu support should explicitly support it? I can see an argument that generalizing operations on multiple gpus without the application domain knowledge is probably not going to work out well. 

Ideally we'd want something like, `CuUnifiedArray <: CuArray`, but Julia does not allow sub-typing on concrete types, only abstract types. Maybe there's an another way to achieve this without having to write a bunch of duplicated code between CuArray and CuUnifiedArray? Perhaps we need a new abstract type something like AbstractCuArray and all common code for array/cuda pointer management can be dispatched on that abstract type?

**Comment by maleadt** [comment]
> I was hoping we can do something similar with `Chain(Dense(...), Dense(...)) |> multigpu` and all operations from there on would work across multiple GPUs.

`multigpu` could use a separate Adaptor for that:

```julia
julia> using Adapt

julia> struct UnifiedCuArray{T} end

julia> Adapt.adapt_storage(::Type{UnifiedCuArray}, xs::AT) where {AT<:AbstractArray} =
         isbitstype(AT) ? xs : CuArray(xs; unified=true)

julia> Adapt.adapt_storage(::Type{<:UnifiedCuArray{T}}, xs::AT) where {T, AT<:AbstractArray} =
         isbitstype(AT) ? xs : CuArray{T}(xs; unified=true)

julia> a = adapt(UnifiedCuArray, rand(1))
1-element CuArray{Float64, 1}:
 0.21031425748621335

julia> is_managed(pointer(a))
true
```

But yeah, for multigpu to work really well we will need optimized operations, and that then may need a separate type. Although I'm not sure CUDA.jl is the right abstraction level for that.

**Comment by akashkgarg** [comment]
Interesting. Yeah I don't mind moving this out of CUDA.jl but I guess it still leaves a type that essentially just "wraps" `CuArray` and provides an almost identical interface that just forwards calls to the underlying `CuArray`? Is there a better way to do this? Is there a better package in which this should live or do we want to create a new package for it?

**Comment by maleadt** [comment]
> I guess it still leaves a type that essentially just "wraps" `CuArray` and provides an almost identical interface that just forwards calls to the underlying `CuArray`?

No. The `UnifiedCuArray` type here is an _adaptor_, an otherwise meaningless struct that Adapt.jl uses to select methods when converting objects from the CPU to the GPU. I just called it like that because the current adaptor re-uses the `CuArray` type too.

**Comment by maleadt** [comment]
Let's continue in https://github.com/JuliaGPU/CUDA.jl/pull/1023.

**Pull request closed without merging**
