### PR TITLE
Switch from manual artifact handling to automated JLLs

### PR DESCRIPTION
**Pull request by maleadt**
This PR switches our manual handling of artifacts (for loading the CUDA toolkit and some of its libraries) to autogenerated JLLs that come directly from Yggdrasil:

- CUDA_Driver_jll: for loading the driver (`libcuda.so`), either from the system or from a forward-compatible package
- CUDA_Runtime_jll: for loading the CUDA toolkit, both libraries (`libcublas`, `libcufft`, etc) and some essential binaries (`ptxas`, `nvdisasm`) and files (`libcudadevrt`, `libdevice`)
- CUDNN_jll, CUTENSOR_jll, cuQuantum_jll (blame @kshyatt for the change in capitalization): for loading libraries that depend on the CUDA toolkit

The above is driven by a `cuda` tag that's put in the host platform, indicating which version of the toolkit has been loaded. This then informs downstream packages like CUDNN_jll which artifact to load. I'm not sure we have this exactly figured out yet, i.e., CUDNN looks to release 11.x builds that are compatible with, well, every CUDA 11.x toolkit, while NCCL has separate 11.0 and 11.8 builds of which I'm not sure how compatible they are with other versions of the toolkit.

This also implies that the env vars we used to steer this, JULIA_CUDA_VERSION and JULIA_CUDA_USE_BINARYBUILDER, have been removed. Instead, the same can be accomplished through Preferences for `CUDA_Runtime_jll`. The version can be conveniently set using `CUDA.set_runtime_version!`, while using a local toolkit needs overrides for each product path (for which there's a helper script in `deps/local.jl`).

Finally, we're doing this not only to simplify things, but because it'll make it possible to build arbitrary binaries that have CUDA dependencies and simply load them by depending on and importing CUDA_Runtime_jll at run time.

### CODE REVIEW

**Comment by sloede** [comment]
@maleadt It would be great if you could give a heads up before this is merged and/or tagged in a new release to provide supercomputer centers a chance to prepare their module files in time, e.g., @omlins @carstenbauer. Also, it would be great if there were a transition guide for both users and cluster operators such that the latter know how to prepare their module files in an appropriate manner (maybe similar to https://juliaparallel.org/MPI.jl/stable/configuration/#Notes-to-HPC-cluster-administrators).

In any case, it's great to see that choosing the appropriate backend libraries becomes easier 👍

**Comment by carstenbauer** [comment]
How does one check if the overriding was successful? I used `deps/local.jl` to generate preferences and it seems to work but how do I know that it is actually using the local CUDA?

**Comment by maleadt** [comment]
> It would be great if you could give a heads up

That was the purpose of the PSA on Slack 🙂  I'm not a HPC user/developer, so please have a look yourself (feel free to propose content for such a transitional guide, but the PR contains documentation already). Also note that the change is accompanied with a breaking version change, so it won't affect current users.

**Comment by maleadt** [comment]
> How does one check if the overriding was successful? I used `deps/local.jl` to generate preferences and it seems to work but how do I know that it is actually using the local CUDA?

`CUDA.versioninfo()` should report different versions. You can also check the path returned by e.g. `CUDA.libcudart`. Ultimately there isn't a way to be sure that everything has been successfully overridden, nor to check with a JLL that its using overridden paths, but that's more of a Pkg/Artifacts/JLLWrappers limitation.

I considered checking in `CUDA.versioninfo()` for each library whether the path resolves to an artifact folder, but that would involve string-matching against every depot dir as well as the artifact override dir, so it seemed too messy.

**Comment by sloede** [comment]
> Also note that the change is accompanied with a breaking version change, so it won't affect current users.

Ah, but it will 🙂: It will have an impact on all users who use such a compute platform and expect CUDA.jl to Just Work (as it does right now, by merit of modules and environment variables). Please note that I am also not a GPU user, I just would like to make sure that we do not make life too hard for our HPC users and sysadmins (who are easily scared).

> That was the purpose of the PSA on Slack 🙂

It would be great if you could give another heads up once everything is tested and the docs/setup procedure are finalized, such that we can start pinging the sysadmins (who often are not Julia users themselves).

**Comment by carstenbauer** [comment]
> while using a local toolkit needs overrides for each product path (for which there's a helper script in `deps/local.jl`).

I think that this functionality should be exposed in a nicer way (i.e. not just as a lonely script in the CUDA.jl repo). For example, MPI.jl exposes [`MPIPreferences.use_system_binary()`](https://juliaparallel.org/MPI.jl/latest/reference/mpipreferences/#MPIPreferences.use_system_binary).

**Comment by maleadt** [comment]
> I considered checking in `CUDA.versioninfo()` for each library whether the path resolves to an artifact folder, but that would involve string-matching against every depot dir as well as the artifact override dir, so it seemed too messy.

I added some functionality to visualize it after all:

```
julia> CUDA.versioninfo()
NVIDIA driver 520.56.6
CUDA driver 11.8
CUDA runtime 11.8 (from local system)

CUDA libraries:
- CUBLAS: 11.11.3 (from local system)
- CURAND: 10.3.0 (from local system)
- CUFFT: 10.9.0 (from local system)
- CUSOLVER: 11.4.1 (from local system)
- CUSPARSE: 11.7.5 (from local system)
- CUPTI: 18.0.0 (from local system)
- NVML: 11.0.0+520.56.6

Toolchain:
- Julia: 1.8.2
- LLVM: 13.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0, 7.1, 7.2
- Device capability support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80, sm_86

1 device:
  0: Quadro RTX 5000 (sm_75, 14.747 GiB / 15.000 GiB available)
```

**Comment by maleadt** [comment]
> I think that this functionality should be exposed in a nicer way (i.e. not just as a lonely script in the CUDA.jl repo). For example, MPI.jl exposes [`MPIPreferences.use_system_binary()`](https://juliaparallel.org/MPI.jl/latest/reference/mpipreferences/#MPIPreferences.use_system_binary).

I'm not sure. Very few users are going to need this, only sysadmins who will need to run this script once and save the preference somewhere globally, so this isn't intended to be a user-facing API.

**Comment by sloede** [comment]
> Very few users are going to need this

Maybe I completely misunderstand the purpose of this PR, but isn't every user who is not using the JLL CUDA version but the vendor-provided one on the respective system going to need this? That is, more or less everyone on an HPC system?

**Comment by carstenbauer** [comment]
> I'm not sure. Very few users are going to need this, only sysadmins who will need to run this script once and save the preference somewhere globally, so this isn't intended to be a user-facing API.

It's everyone who wants to use a local CUDA. Not just sysadmins but also, for example, users on HPC systems where the sysadmins don't know of or don't care about julia, which, unfortunately, might be the majority. (Also this would be a "regression" in the sense that previously I could readily switch to a local installation by just specifying an env variable and now I have to look up a single script file in a repo)

More importantly, in its current form, the script puts specific paths into the `LocalPreferences.toml`. This makes the preferences CUDA (module)-version dependent. Hence, the script would at least need to be run whenever a new CUDA version is released. Note though, that for me the following (i.e. dropping the specific paths since the corresponding env variables are properly set) also seems to work which would avoid the version dependency.
```
[CUDA_Runtime_jll]
compute_sanitizer_path = "compute-sanitizer"
libcublas_path = "libcublas.so"
libcudadevrt_path = "libcudadevrt.a"
libcudart_path = "libcudart.so"
libcufft_path = "libcufft.so"
libcupti_path = "libcupti.so"
libcurand_path = "libcurand.so"
libcusolverMg_path = "libcusolverMg.so"
libcusolver_path = "libcusolver.so"
libcusparse_path = "libcusparse.so"
libdevice_path = "libdevice.10.bc"
libnvtoolsext_path = "libnvToolsExt.so"
libnvvm_path = "libnvvm.so"
nvdisasm_path = "nvdisasm"
nvlink_path = "nvlink"
ptxas_path = "ptxas"
```

**Comment by maleadt** [comment]
> Note though, that for me the following (i.e. dropping the specific paths since the corresponding env variables are properly set) also seems to work which would avoid the version dependency.

That doesn't work. I'm not even sure it actually looks in PATH/LD_LIBRARY_DIR when the path is relative, but I can guarantee that for ordinary files it doesn't do a local filesystem scan (obviously), and that's exactly what `libdevice` and `libcudadevrt` are.

**Comment by maleadt** [comment]
> Maybe I completely misunderstand the purpose of this PR, but isn't every user who is not using the JLL CUDA version but the vendor-provided one on the respective system going to need this? That is, more or less everyone on an HPC system?

Have you tried the artifacts on your cluster? They're the official NVIDIA binaries so generally should work fine.

**Comment by maleadt** [comment]
> Also this would be a "regression" in the sense that previously I could readily switch to a local installation by just specifying an env variable and now I have to look up a single script file in a repo

Yeah, but it was a pain to maintain, and made it impossible to integrate with the rest of the Julia binary wrappers ecosystem. You win some you lose some :shrug:

**Comment by carstenbauer** [comment]
> That doesn't work.

It *does* work in the sense that I can actually run a GPU computation (I tried). Are you saying that I might be unknowingly/implicitly using the regular artifact-provided binaries?

> I'm not even sure it actually looks in PATH/LD_LIBRARY_DIR when the path is relative, but I can guarantee that for ordinary files it doesn't do a local filesystem scan (obviously), and that's exactly what `libdevice` and `libcudadevrt` are.

Not sure I understand, in particular who/what is "it" here? My thought was that with these overrides the artifact should just export these relative paths for the lib* products, i.e. e.g. `CUDA_Runtime_jll.libdevice_path == "libdevice.10.bc"` and when CUDA.jl tries to use them, i.e. with a ccall, it will be automatically found because it is on LD_LIBRARY_PATH and similar. Where am I wrong?

**Comment by carstenbauer** [comment]
> Have you tried the artifacts on your cluster? They're the official NVIDIA binaries so generally should work fine.

It's not just a matter of if they work (and sometimes they don't). For example:

1) HPC cluster sysadmins tend to want to reuse the already existing software to avoid having every single user install there own CUDA (e.g. in the form of a Julia artifact). For one, to avoid wasting disk space (~O(users)) but also because they don't want to provide support for custom user installations (if there already are well-configured system-wide installations available).
2) As of now, we don't have CUDA-aware MPI in Yggdrasil. I need to use a specific combination of CUDA and MPI modules provided by the sysadmins for this to work.

(Let me comment that, personally, I am not a big supporter of the first argument. Unfortunately, many sysadmins are and if we care about Julia on HPC clusters we need to provide options to use local software instead of artifacts alone.)

(Also AFAIR, if I override the product paths of the artifact the binary dependencies will nevertheless be downloaded and never used because we don't really have lazy downloading here. So the disk space wasting will already happen, no matter what. But this is a more general issue of course.)

**Comment by carstenbauer** [comment]
> Yeah, but it was a pain to maintain, and made it impossible to integrate with the rest of the Julia binary wrappers ecosystem. You win some you lose some 🤷

I feel you, I really do. And I would say that it's fine to loose some of the comfort if that makes the maintenance much easier. But IMO allowing users to opt-out of (parts) of the artifact story is really important and shouldn't be made unnecessarily hard or neglected entirely.

**Comment by ViralBShah** [comment]
Can we do this incrementally? We do need to keep moving forward, because we can't build libraries that depend on CUDA today in Yggdrasil at all. Would it not be possible to get this merged, and incrementally improve it for the HPC cluster use case? Note, this is not just a CUDA issue - HPC clusters also want users to not bring their own MPI, MKL, and many other system libraries. So the problem is not just CUDA specific (but because it touches drivers and such, it may have higher visibility).

**Comment by ViralBShah** [comment]
I feel disk space wasting is less than ideal - but in the grand scheme of things not a real issue. All of this is a tiny fraction of the actual usage on an HPC cluster anyways.

**Comment by sloede** [comment]
Not being able to select system-provided binaries for CUDA will kill the ability to use CUDA.jl on some systems where the CUDA binaries are patched to make them play nice with the rest of the software stack. I can understand the need to move forward, but I see the risk of considerably alienating a part of the user community that usually is one of the most ardent supports of Julia and what it brings to the table.

**Comment by ViralBShah** [comment]
My only request is to not hold up this PR, which is already substantial. Having an escape hatch is not difficult, and we should be able to work on it all together and get it. I know the HPC community is the biggest supporter, and I interact with many of those users myself. 

But there are two separate points here:
1. Provide override mechanism so that system libs can be used
2. Don't even install the artifacts (to avoid wasted disk space)

I think 1. is the more important think, and 2. is a nice to have optimization.

**Comment by maleadt** [comment]
Let's take a step back here. First and foremost, no functionality is being lost: CUDA.jl with JLLs still allows selecting an local system toolkit, as expected by HPC users, and I don't intend to remove that functionality. The usability of said feature is changing a little, it's not as dynamic as it used to be, but in terms of functionality there is no change. In fact, if you check the CI logs you can see that the `deps/local.jl` script is even used for a significant number of tests to ensure it keeps working as expected.

Once we get the JLL set-up working, which is what the entire Julia ecosystem is evolving towards, I'm happy to work towards / take PRs that improve this functionality for specific groups of users.

**Comment by maleadt** [comment]
> i.e. e.g. `CUDA_Runtime_jll.libdevice_path == "libdevice.10.bc"` and when CUDA.jl tries to use them, i.e. with a ccall, it will be automatically found because it is on LD_LIBRARY_PATH and similar. Where am I wrong?

`libdevice` is a bitcode library, notice the `.bc` extension. This file isn't on any autodiscoverable path (like PATH for binaries or LD_LIBRARY_PATH for libraries).

**Comment by carstenbauer** [comment]
> `libdevice` is a bitcode library, notice the `.bc` extension. This file isn't on any autodiscoverable path (like PATH for binaries or LD_LIBRARY_PATH for libraries).

Ah, didn't know that. Does my logic apply to the other libraries / binaries though? As I said, it works in practice (at least to the extent that I tested it) and I'd like to understand why (i.e. what is used).

**Comment by carstenbauer** [comment]
> My only request is to not hold up this PR, which is already substantial.

Sure! FWIW, I never intended to argue against this PR. I just tested the new mechanism and pointed out some inconveniences, e.g. having to use a standalone file (`deps/local.jl`) to generate the preferences, as well as problems that will arise, in particular on HPC clusters. I do know that this PR enables a lot of great routes towards CUDA-dependent artifacts which is arguably very important.

**Comment by sloede** [comment]
I second @carstenbauer's statement!

**Comment by ViralBShah** [comment]
Maybe open new issues to track the inconveniences for HPC clusters?

**Comment by maleadt** [comment]
In light of the comments above I reworked the local toolkit discovery, adding features that seem important for HPC users:
- API for setting the preference: `CUDA.set_runtime_version!("local")`
- `LocalPreferences.toml` contains a toggle, no hard-coded paths
- If the version is `"local"`, CUDA_Runtime_Discovery.jl will be used to discover paths at run time (i.e. they won't be baked in the precompilation image)
- Also, if the version is `"local"`, no artifacts will be downloaded (on the condition that this preference was set before ever precompiling CUDA.jl, so using the above API won't work for that)

I hope that sufficiently deals with the concerns raised here. Please test this out and let me know, as I want to merge this soon.

**Comment by maleadt** [comment]
> * If the version is `"local"`, CUDA_Runtime_Discovery.jl will be used to discover paths at run time (i.e. they won't be baked in the precompilation image)

Do note that the result of this is that setting the toolkit to `"local"` explicitly opts out of using *any* CUDA-related JLL, because those need to be resolved at compile time.

**Comment by carstenbauer** [comment]
Thanks a lot @maleadt, I will test things later today (as soon as I can find time for it).

**Comment by carstenbauer** [comment]
Tried it and seems to work just fine. Thanks again!

> Do note that the result of this is that setting the toolkit to `"local"` explicitly opts out of using _any_ CUDA-related JLL, because those need to be resolved at compile time.

Besides `version="local"`, is it still possible to override the artifact product paths via preferences explicitly (like previously in this PR)? I take it that if one does this (accepting the unnecessary download of artifacts) your comment doesn't apply and other CUDA-related JLLs would work, correct? (TBC, I wouldn't mind if this doesn't work anymore and one has to make a clean decision, either local CUDA or JLL CUDA.

**Comment by maleadt** [comment]
> Besides `version="local"`, is it still possible to override the artifact product paths via preferences explicitly (like previously in this PR)?

Yes, that's a feature of the JLLWrappers-generated code, and you just want to set preferences like `libcublasrt_path` on `CUDA_Runtime_jll` (i.e., what `deps/local.jl` used to generate) without having set the version to `"local"`. I wouldn't recommend it though, because (1) it is then possible to only partially override an artifact (or, less intentionally so when you forget to override a product), and (2) it may result in the CUDA platform tag (which contains the toolkit version, and is determined based on the CUDA driver) to be different from the actual version being used, resulting in incompatible artifacts being loaded by other CUDA-related JLLs. You can avoid the latter by also setting the `version` preference, which overrides the platform tag.

So it's possible, but finicky. The alternative is that code that uses JLLs does something like:

```
if CUDA_Runtime_jll.is_available()
  using CUDNN_jll
else
  const libcudnn = "libcudnn"
end
```

**Comment by JBlaschke** [comment]
> I'm not sure. Very few users are going to need this, only sysadmins who will need to run this script once and save the preference somewhere globally, so this isn't intended to be a user-facing API.

I disagree! Strongly! Our admin time at NERSC is very expensive, so introducing toil, such as this and shrugging it off as "just let the admins do it" makes me mad. (maybe because I'm an admin).

It's worth noting that we like to enable as much flexibility in our setup as possible, so I very much like the idea of "here is an intuitive API, have at it" in addition to sensibly defined defaults in a global location.

**Comment by JBlaschke** [comment]
> Yeah, but it was a pain to maintain, and made it impossible to integrate with the rest of the Julia binary wrappers ecosystem. You win some you lose some shrug

@maleadt I'll be honest -- I am miffed. Not because of this change, but the fact that it was introduced very quickly -- practically without warning considering the software release cycle on big supercomputers.

Have you heard about deprecation warnings? I guess sometimes you win some, and sometimes you loose support from the DOE :shrug:

**Comment by JBlaschke** [comment]
> I feel you, I really do. And I would say that it's fine to loose some of the comfort if that makes the maintenance much easier. But IMO allowing users to opt-out of (parts) of the artifact story is really important and shouldn't be made unnecessarily hard or neglected entirely.

@carstenbauer You put it much nicer than me (probably got a nice cup of mint tea before typing your reply) -- much appreciated. Thanks to my the others in this thread (@sloede and @ViralBShah ) who where on top of this, and triaged this PR before I could get to checking my messages.

@maleadt I also appreciate that you're listening to the HPC community. In case some of my more flamboyant communication style is reprieved as aggressive, let me take the opportunity to make sure to thank you for attempting to balance competing interests.

RE my remarks about loosing DOE support over this -- I want to share with @maleadt a scenario: I'm not exaggerating when I say that I am currently the only one on the NERSC staff devoting a considerable amount of time to support -- and advocate for -- Julia. If we don't settle on a sensible low-effort solution to use the system binaries, some of this support will look like: "Here's a script. Run it. And if it doesn't work, heck, then I don't know ether ... try Tim". Worse still, management my ask: "how much staff effort would we need to invest in supporting Julia?". If I said "2 to 3 FTE's", then there is a real risk that they'll decide that we can't afford to support Julia.

**Comment by JBlaschke** [comment]
> I feel disk space wasting is less than ideal - but in the grand scheme of things not a real issue. All of this is a tiny fraction of the actual usage on an HPC cluster anyways.

@ViralBShah I disagree -- users readily bump into the limits of their quota (we have 8000 users, so even a modest quota would scale up to obscene amounts when considering the full file system) thanks to anaconda. This can be pretty painful for users as  they are forced triage space on the global fast file systems.

**Comment by JBlaschke** [comment]
> Maybe open new issues to track the inconveniences for HPC clusters?

@ViralBShah Please do!

**Comment by JBlaschke** [comment]
https://cuda.juliagpu.org/stable/installation/overview/#Local-installation doesn't seem to have the "new" way of doing this and needs updating. I guess it has to be regenerated to bring it into line with https://github.com/JuliaGPU/CUDA.jl/blob/master/docs/src/installation/overview.md#using-a-local-cuda ? (I actually don't know how the pages are rendered so I wanted to bring this up here.

There has been some frayed nerves on my end -- so I will ask @maleadt here: If an HPC center wanted to use the local CUDA install by default. Am I correct in understanding that that's handled using a global `Preferences.toml` containing:
```toml
[CUDA_Runtime_jll]
version = "local"
```

**Comment by maleadt** [comment]
@JBlaschke Let's stay level-headed and try and improve CUDA.jl in a way that suits all users. I'm only going to respond to the strictly technical portions of your comments, since I, as you correctly presumed, do not appreciate the general tone.

> I am miffed. Not because of this change, but the fact that it was introduced very quickly -- practically without warning considering the software release cycle on big supercomputers.

This PR was merged relatively quickly for technical reasons (other PRs easily causing conflicts). As noted above, a release of these changes is still quite some time off, and will be accompanied by a breaking version release so it should not impact user code that relies on current behavior. So there is still ample time to improve.

> Have you heard about deprecation warnings?

I have. It's not possible to deprecate the entire code loading mechanism, hence the breaking release.

> If we don't settle on a sensible low-effort solution to use the system binaries [...]

What do you not like about the new API then? In case you missed the changes I did after Carsten's comments, it's now just a matter of calling `CUDA.set_runtime_version!("local")` and re-starting Julia, which seems almost identical to setting an environment variable and re-starting Julia.

>> I feel disk space wasting is less than ideal - but in the grand scheme of things not a real issue. All of this is a tiny fraction of the actual usage on an HPC cluster anyways.
>
> @ViralBShah I disagree -- users readily bump into the limits of their quota (we have 8000 users, so even a modest quota would scale up to obscene amounts when considering the full file system) thanks to anaconda. This can be pretty painful for users as they are forced triage space on the global fast file systems.

Again, maybe you missed my latest changes, but CUDA.jl does not needlessly download any artifacts anymore if the version is set to `"local"`. Since that's done by a preference, this could be globally installed (e.g. provided by the cluster's module system). If that doesn't work, or needs improvements on the Preferences.jl side, please open specific issues.

> https://cuda.juliagpu.org/stable/installation/overview/#Local-installation doesn't seem to have the "new" way of doing this and needs updating.

That's expected, note the `stable` in the URL. If you click the `dev docs` button in the README instead, you end up on the development version of the documentation (again, because this is part of an unreleased version), which contains the updated content: https://cuda.juliagpu.org/dev/installation/overview/#CUDA-toolkit

> If an HPC center wanted to use the local CUDA install by default. Am I correct in understanding that that's handled using a global Preferences.toml containing:
>
> ```
> [CUDA_Runtime_jll]
> version = "local"
> ```

Correct, that's how it's intended to work. So please test this out, and if there's issues, I'd be happy to help you resolve them or further improve CUDA.jl so that it works well for HPC users.

**Comment by ViralBShah** [comment]
@JBlaschke Thanks for chiming in, and thanks to @maleadt for incorporating all the feedback.

**Comment by JBlaschke** [comment]
@maleadt I think I was being unfair to you, and my criticism was too harsh. So I want to make a public apology. Now that I understand the context a little better -- and that there are safeguards in package system that would have prevented a silent failure -- it's clear that I overreacted.

**Comment by JBlaschke** [comment]
I think this is in good shape.  To summarize various out-of-thread discussions:
1) The HPC centers might need to implement a test that checks if artifact overwriting works in their CI
2) It is absolutely crucial to include an "escape hatch" for compiled artifacts (at least until we can force system integrators to work with unpatched libraries). I think it's crucial to make sure that this works with as little toil as possible. Otherwise we run the risk of our own two language problem (Julia for HPC, and the rest)
3) Run-time library resolution has problems as APIs change -- and therefore need recompilation. I think it's important to have this nevertheless as a safety net. @vchuravy pointed out that we could also test the idea of using Lmod to generate preference files (which would be generated whenever the `cudatoolkit` etc modules are generated). @sloede @carstenbauer 
4) The `version = "local"` is a good fallback solution. @maleadt we might want to track HPC compatibility issues and where to go from here in its own dedicated issue like @ViralBShah said.

**Comment by JBlaschke** [comment]
I think there is one last issue @maleadt -- looking at https://github.com/JuliaGPU/CUDA.jl/blob/52a16d6b213759fb339fe3325627786799c9a6e8/src/initialization.jl#L119-L125 an error is emitted when the env var is set. We use the approach of setting configurations globally, so that users have "good" defaults and are free to install their own variants if needed. What do you think should be the solution for when different users have different `CUDA.jl` versions, or even the same users have multiple versions of `CUDA.jl`?

One option could be to make a module that switches from the env var to the `Preferences.toml`. But I would prefer to require as few "special steps" users need to take. Any thoughts?

**Comment by vchuravy** [comment]
Yeah maybe not warning if the preference is set to `local`

**Pull request merged**
