### PR TITLE
Add support for CUDA 12.1

### PR DESCRIPTION
**Pull request by maleadt**
cc @amontoison, hopefully this goes smoother than the previous upgrade 🙂
I take it we should be able to remove the workarounds put in place for 12.0 now?

### CODE REVIEW

**Comment by amontoison** [comment]
@maleadt We don't need to modify something for CUDA 12.1.0. If all tests passed that's fine :smiley: 
I will just re-enable some tests with the version 12.1.1:
- https://github.com/JuliaGPU/CUDA.jl/blob/master/test/cusparse/conversions.jl#L78
- https://github.com/JuliaGPU/CUDA.jl/blob/master/test/cusparse/conversions.jl#L142

Don't forget to regenerate the wrappers.

**Comment by amontoison** [comment]
Don't forget to regenerate the wrappers :wink:

**Comment by maleadt** [comment]
> I will just re-enable some tests with the version 12.1.1:

Let me try enabling those.



> Don't forget to regenerate the wrappers.

That's not required? It's a minor version so should be backwards compatible; only if you want to use newer features you need updated headers. Ideally we'd have separate versions for each CUDA version, but that would mean we'd need to decide at precompilation time which toolkit to use, and we currently don't have that.

**Comment by amontoison** [comment]
> > I will just re-enable some tests with the version 12.1.1:
> 
> Let me try enabling those.

Great! they solved the issue in this version 12.1.0.

> > Don't forget to regenerate the wrappers.
> 
> That's not required? It's a minor version so should be backwards compatible; only if you want to use newer features you need updated headers. Ideally we'd have separate versions for each CUDA version, but that would mean we'd need to decide at precompilation time which toolkit to use, and we currently don't have that.

No, it's not required but it's easier to keep track of when new features were added for the tests.
NVIDIA also deprecates some routines for more recent ones with minor version of CUDA and we can add the interfaces over time and not when we have a new breaking release.
The release notes of NVIDIA are not exhaustive.

**Pull request merged**
