### PR TITLE
Add EnzymeCore extension for parent_job

### PR DESCRIPTION
**Pull request by vchuravy**
Alternative to #2260, depends on https://github.com/EnzymeAD/Enzyme.jl/pull/1328

### CODE REVIEW

**Review by maleadt — APPROVED** [review]
LGTM!

Marking as draft since the dependent PR hasn't been merged yet (to save on CI resources).

**Comment by vchuravy** [comment]
Okay this should be ready now.

**Comment by maleadt** [comment]
Looks like NNlib will need an EnzymeCore compat bump for CI to pass here (normally we detect installation issues of downstream packages and soft-fail that job, but here EnzymeCore is only a test dep so the failure happens during `Pkg.test`).

**Comment by wsmoses** [comment]
here's the NNlib bump: https://github.com/FluxML/NNlib.jl/pull/571

**Comment by michel2323** [comment]
This works for https://github.com/JuliaGPU/KernelAbstractions.jl/pull/454 . Can we merge this?

**Comment by vchuravy** [comment]
We need Enzyme.jl v0.12 to be released. Otherwise we make Enzyme and CUDA uninstallable together.

**Comment by michel2323** [comment]
Enzyme v0.12 is [released](https://github.com/EnzymeAD/Enzyme.jl/releases/tag/v0.12.0) Let me know if there's something I can do.

**Comment by wsmoses** [comment]
@vchuravy these test failures seem unrelated. good to go?

**Comment by maleadt** [comment]
Yeah, the sorting failure is https://github.com/JuliaGPU/CUDA.jl/issues/2331. I've restarted the job.

**Pull request merged**
