### PR TITLE
add median function in statistics (when dim is mention, scalar operation)

### PR DESCRIPTION
**Pull request by michiboo**
for #265

### CODE REVIEW

**Comment by maleadt** [comment]
Thanks! Could you add some tests that compare to the Base implementation to `test/statistics.jl`?

**Comment by maleadt** [comment]
Just saw the `(when dim is mention, scalar operation)` in your title; that's not OK since tests run with scalar iteration disallowed. Either remove that from the test suite, or add support for passing a dims keyword.

EDIT: I fail to see the purpose of this PR then, since `median` without specifying `dims` already works...

**Comment by michiboo** [comment]
@maleadt  
at the moment we cannot get median for each row:

```
julia> a = CuArray([1 2 3; 4 5 6])
2×3 CuArray{Int64,2,Nothing}:
 1  2  3
 4  5  6
julia> CUDA.median(a, 2)
ERROR: MethodError: no method matching median(::CuArray{Int64,2,Nothing}, ::Int64)
```

or if we don't specify dims then it will consider median for all values

But when we merged this PR and when we specify dims in median:

```
julia> a = CuArray([1 2 3; 4 5 6])
2×3 CuArray{Int64,2,Nothing}:
 1  2  3
 4  5  6

julia> CUDA.median(a, 2)
┌ Warning: Performing scalar operations on GPU arrays: This is very slow, consider disallowing these operations with `allowscalar(false)`
└ @ GPUArrays ~/.julia/packages/GPUArrays/X4SqE/src/host/indexing.jl:43
2×1 CuArray{Float64,2,Nothing}:
 2.0
 5.0
```

here we get median for each row.

**Comment by maleadt** [comment]
Please use triple backticks to delimit code blocks.

> julia> CUDA.median(a, 2)
> ERROR: MethodError: no method matching median(::CuArray{Int64,2,Nothing}, ::Int64)

You are using `median` wrong:

```julia
julia> a = CuArray([1 2 3; 4 5 6])
2×3 CuArray{Int64,2,Nothing}:
 1  2  3
 4  5  6

julia> using Statistics

julia> median(a; dims=2)
┌ Warning: Performing scalar operations on GPU arrays: This is very slow, consider disallowing these operations with `allowscalar(false)`
└ @ GPUArrays ~/Julia/pkg/GPUArrays/src/host/indexing.jl:43
2×1 CuArray{Float64,2,Nothing}:
 2.0
 5.0
```

**Comment by michiboo** [comment]
@maleadt  Thanks for the editing and comment

If we using Statistics for median then I think it's best to remove  "median : Scalar operation when dims is mentioned" for #265

**Comment by maleadt** [comment]
> If we using Statistics for median then I think it's best to remove "median : Scalar operation when dims is mentioned" for #265

No, I think you misunderstand the issue: it documents _problems_ with certain methods from Statistics, like `median`, which trigger scalar iteration. The goal is not to replace that method with a custom `CUDA.median` by performing scalar iteration, but by implementing `Statistics.median` in a way that it **doesn't** perform scalar iteration.

**Comment by maleadt** [comment]
Did you test this? You implement the wrong `median` method (dims arg instead of dims kwarg), and the reshape does not work when passing multiple dims (e.g. `median(rand(2,2,2), dims=[1,3])`). There's also a syntax error in the tests.

Furthermore, launching `N` kernels, one for every slice to reduce, is not going to perform well, we really need a single kernel that processes all dimensions at once (or multiple ones, but not a number per dimension). This kind of `mapslices` operation, where we want to apply a vectorized operation across dimensions, has been an issue before because the GPU programming model really wants a scalar operation to apply to every element (although that application can be different for each dimension).

**Comment by michiboo** [comment]
@maleadt  can you link me to the issue that fixed mapslices operation before? TBH I am having trouble replacing the mapslices operations. I thought the reshape should be a good replacement as there is no warning shown

**Comment by maleadt** [comment]
Sorry, I should have been more clear: We currently don't have a GPU-compatible `mapslices` because of exactly that problem. For a GPU implementation of `median`, additionally supporting the `dims` keyword, we probably first need an implementation of some sorting functions, which we also lack.

**Pull request closed without merging**
