### PR TITLE
Add `sind`/`cosd`

### PR DESCRIPTION
**Pull request by navidcy**
This PR adds CUDA-aware implementation for `sind` and `cosd` (`sin`/`cos` when argument is in degrees).

### CODE REVIEW

**Comment by navidcy** [comment]
@vchuravy I don't feel I quite understand what's happening here to actually remedy what we discussed at https://github.com/CliMA/Oceananigans.jl/issues/2371

**Comment by vchuravy** [comment]
So the goal is that we want tor replace a GPU incompatible implementation with a GPU compatible one. `@device_override Base.sind(x::Float32) = ...` simply says that for the function `sind` when we want to compile code for the GPU we should use the new implementation.

Now most of the code here actually falls back onto Nvidia intrinsics, but there are none for for `sind` and `cosd`.

But on the other hand this already works?

```
A = CUDA.rand(64)
cosd.(A)
sind.(A)
```

So I am not sure there is anything to do here?

But if there is, then it would be as simple as:

```
@device_override Base.sind(φ::Union{Float32, Float64}) = cos(π * φ / 180) 
```

Modulo the question if that definition is accurate enough.

**Comment by navidcy** [comment]
gotcha

**Comment by maleadt** [comment]
> But on the other hand this already works?
> 
> ```
> A = CUDA.rand(64)
> cosd.(A)
> sind.(A)
> ```

So we don't need this? Or what's wrong with the Base implementation? It seems much more advanced, https://github.com/JuliaLang/julia/blob/feb7b774525830096b6a8a592becdd73f8789415/base/special/trig.jl#L1190-L1245

**Comment by navidcy** [comment]
> So we don't need this? Or what's wrong with the Base implementation? It seems much more advanced, https://github.com/JuliaLang/julia/blob/feb7b774525830096b6a8a592becdd73f8789415/base/special/trig.jl#L1190-L1245

Seems so “advanced” that we are having compilation issues on the gpu in Oceananigans.jl…
See https://github.com/CliMA/Oceananigans.jl/issues/2371

**Comment by maleadt** [comment]
> Seems so “advanced” that we are having compilation issues on the gpu in Oceananigans.jl…

The "last we tried" there doesn't match @vchuravy's demo above. I'd rather not carry needless overrides to Base methods. If they only work on recent versions, add a version bound.

**Comment by navidcy** [comment]
cc @glwagner

**Comment by glwagner** [comment]
If I'm remembering correctly, I think that simple kernels like that produced by `sind.(A)` compile just fine, but that we run into problems when `Base.sind` is inlined into massive kernels like the ones that Oceananigans often uses. We could look into this again over at Oceananigans.

But I agree with @maleadt this doesn't motivate replacing the nice Base versions of `sind` / `cosd` in CUDA.jl.

**Pull request closed without merging**
