### PR TITLE
remove mutable to make device sparse type bitstype

### PR DESCRIPTION
**Pull request by Roger-luo**
I wasn't sure why I added `mutable` to other device sparse types, this is just a fix to #1106 

However, when I testing this locally, I find on 1.7-rc1 even I remove the `mutable`, all the sparse device types are not isbitstype anymore, e.g

```julia
isbitstype(CuSparseDeviceMatrixCSC{Float32, Cint}) # false
``` 

anyone knows why?

### CODE REVIEW

**Comment by maleadt** [comment]
You can try using this from GPUCompiler to explain why: https://github.com/JuliaGPU/GPUCompiler.jl/blob/2c4a3046cdd25e0f0281a8e9c7bc1393461888d1/src/validation.jl#L42-L54

**Comment by Roger-luo** [comment]
The strangest thing is `explain_nonisbits` doesn't work, 1.7-rc1 gives the following

```julia
julia> isbitstype(dt)
false

julia> isbitstype.(fieldtypes(dt))
(true, true, true, true)

julia> dt
CuSparseDeviceVector{Float32, Int32}

julia> ismutabletype(dt)
false
```

but everything is fine on 1.6, maybe it's a bug on 1.7-rc1?

**Comment by maleadt** [comment]
Wouldn't it be better to include the address space as a type parameter, like CuDeviceArray? Maybe you want to create a sparse array in shared memory, for example.

**Comment by maleadt** [comment]
Looks good. Thanks!

**Pull request merged**
