### PR TITLE
include potri and test

### PR DESCRIPTION
**Pull request by erathorn**
This mirrors PR #730 from CuArrays

> This PR addes potri! and accompanying tests.
> Possibly an improvement to #440 (from CuArrays)

### CODE REVIEW

**Comment by maleadt** [comment]
bors try

**Comment by maleadt** [comment]
`allowscalar` and `unsafe_free` have already been imported into CUSOLVER, so you don't need to specify.

**Comment by erathorn** [comment]
The relevant tests seem to pass on my machine.

**Comment by erathorn** [comment]
bors try

**Comment by maleadt** [comment]
Please don't commit merge conflicts and their resolution; you should rebase on top of master.

**Comment by erathorn** [comment]
Sorry for the mess. I cleaned up the code and messages.

**Comment by maleadt** [comment]
```
 Error in testset cusolver:
Error During Test at /builds/JuliaGPU/CUDA.jl/test/cusolver.jl:43
  Got exception outside of a @test
  could not load symbol "cusolverDnZpotri_bufferSize":
  /builds/JuliaGPU/CUDA.jl/.julia/artifacts/9c5665f3f80231f7ed3afa44d46dfd8f8fd7c5c2/lib/libcusolver.so: undefined symbol: cusolverDnZpotri_bufferSize
```

You'll have to guard the functionality and its tests on the `version()`.

EDIT: actually, only guard the tests, but maybe add a `!!! note` to the docstrings about compatibility.

**Comment by erathorn** [comment]
I added the guards for the test and a `!!! note` at `potri()`.

**Pull request merged**
