### PR TITLE
Extend and switch to the new CUDA RNG

### LINKED ISSUE #1081: Support for generating Float16 random numbers
`ComplexF16` fails too. everything else seems to work.  happy to lend a hand if you point me in the right direction.

```
julia> using CUDA

julia> CUDA.rand(Float32, 3)
3-element CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}:
 0.468105
 0.6258179
 0.7012832

julia> CUDA.rand(Float16, 3)
ERROR: InvalidIRError: compiling kernel #53(CUDA.CuKernelContext, CuDeviceVector{Float16, 1}, CuDeviceVector{NTuple{4, UInt32}, 1}) resulted in invalid LLVM IR
Reason: unsupported dynamic function invocation (call to make_rand_num)
Stacktrace:
 [1] gpu_rand
   @ ~/.julia/dev/GPUArrays/src/host/random.jl:35
 [2] #53
   @ ~/.julia/dev/GPUArrays/src/host/random.jl:88
Stacktrace:
  [1] check_ir(job::GPUCompiler.CompilerJob{GPUCompiler.PTXCompilerTarget, CUDA.CUDACompilerParams, GPUCompiler.FunctionSpec{GPUArrays.var"#53#54"{Float16}, Tuple{CUDA.CuKernelContext, CuDeviceVector{Float16, 1}, CuDeviceVector{NTuple{4, UInt32}, 1}}}}, args::LLVM.Module)
    @ GPUCompiler ~/.julia/dev/GPUCompiler/src/validation.jl:111
  [2] macro expansion
    @ ~/.julia/dev/GPUCompiler/src/driver.jl:319 [inlined]
  [3] macro expansion
    @ ~/.julia/packages/TimerOutputs/ZQ0rt/src/TimerOutput.jl:236 [inlined]
  [4] macro expansion
    @ ~/.julia/dev/GPUCompiler/src/driver.jl:317 [inlined]
  [5] emit_asm(job::GPUCompiler.CompilerJob, ir::LLVM.Module; strip::Bool, validate::Bool, format::LLVM.API.LLVMCodeGenFileType)
    @ GPUCompiler ~/.julia/dev/GPUCompiler/src/utils.jl:62
  [6] cufunction_compile(job::GPUCompiler.CompilerJob)
    @ CUDA ~/.julia/dev/CUDA/src/compiler/execution.jl:317
  [7] cached_compilation(cache::Dict{UInt64, Any}, job::GPUCompiler.CompilerJob, compiler::typeof(CUDA.cufunction_compile), linker::typeof(CUDA.cufunction_link))
    @ GPUCompiler ~/.julia/dev/GPUCompiler/src/cache.jl:89
  [8] cufunction(f::GPUArrays.var"#53#54"{Float16}, tt::Type{Tuple{CUDA.CuKernelContext, CuDeviceVector{Float16, 1}, CuDeviceVector{NTuple{4, UInt32}, 1}}}; name::Nothing, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ CUDA ~/.julia/dev/CUDA/src/compiler/execution.jl:288
  [9] cufunction
    @ ~/.julia/dev/CUDA/src/compiler/execution.jl:282 [inlined]
 [10] macro expansion
    @ ~/.julia/dev/CUDA/src/compiler/execution.jl:102 [inlined]
 [11] #launch_heuristic#233
    @ ~/.julia/dev/CUDA/src/gpuarrays.jl:17 [inlined]
 [12] #gpu_call#1
    @ ~/.julia/dev/GPUArrays/src/device/execution.jl:68 [inlined]
 [13] gpu_call(::GPUArrays.var"#53#54"{Float16}, ::CuArray{Float16, 1, CUDA.Mem.DeviceBuffer}, ::CuArray{NTuple{4, UInt32}, 1, CUDA.Mem.DeviceBuffer})
    @ GPUArrays ~/.julia/dev/GPUArrays/src/device/execution.jl:48
 [14] rand!(rng::GPUArrays.RNG, A::CuArray{Float16, 1, CUDA.Mem.DeviceBuffer})
    @ GPUArrays ~/.julia/dev/GPUArrays/src/host/random.jl:85
 [15] rand!(A::CuArray{Float16, 1, CUDA.Mem.DeviceBuffer})
    @ CUDA ~/.julia/dev/CUDA/src/random.jl:129
 [16] rand(::Type, ::Int64)
    @ CUDA ~/.julia/dev/CUDA/src/random.jl:145
 [17] top-level scope
    @ REPL[3]:1
 [18] top-level scope
    @ ~/.julia/dev/CUDA/src/initialization.jl:65

julia> CUDA.rand(ComplexF32, 3)
3-element CuArray{ComplexF32, 1, CUDA.Mem.DeviceBuffer}:
  0.8863116f0 + 0.26660195f0im
 0.19040972f0 + 0.3603402f0im
 0.35977384f0 + 0.29421204f0im

julia> CUDA.rand(ComplexF16, 3)
ERROR: InvalidIRError: compiling kernel #53(CUDA.CuKernelContext, CuDeviceVector{ComplexF16, 1}, CuDeviceVector{NTuple{4, UInt32}, 1}) resulted in invalid LLVM IR
Reason: unsupported dynamic function invocation (call to make_rand_num)
Stacktrace:
 [1] gpu_rand
   @ ~/.julia/dev/GPUArrays/src/host/random.jl:35
 [2] gpu_rand
   @ ~/.julia/dev/GPUArrays/src/host/random.jl:57
 [3] #53
   @ ~/.julia/dev/GPUArrays/src/host/random.jl:88
Stacktrace:
  [1] check_ir(job::GPUCompiler.CompilerJob{GPUCompiler.PTXCompilerTarget, CUDA.CUDACompilerParams, GPUCompiler.FunctionSpec{GPUArrays.var"#53#54"{ComplexF16}, Tuple{CUDA.CuKernelContext, CuDeviceVector{ComplexF16, 1}, CuDeviceVector{NTuple{4, UInt32}, 1}}}}, args::LLVM.Module)
    @ GPUCompiler ~/.julia/dev/GPUCompiler/src/validation.jl:111
  [2] macro expansion
    @ ~/.julia/dev/GPUCompiler/src/driver.jl:319 [inlined]
  [3] macro expansion
    @ ~/.julia/packages/TimerOutputs/ZQ0rt/src/TimerOutput.jl:236 [inlined]
  [4] macro expansion
    @ ~/.julia/dev/GPUCompiler/src/driver.jl:317 [inlined]
  [5] emit_asm(job::GPUCompiler.CompilerJob, ir::LLVM.Module; strip::Bool, validate::Bool, format::LLVM.API.LLVMCodeGenFileType)
    @ GPUCompiler ~/.julia/dev/GPUCompiler/src/utils.jl:62
  [6] cufunction_compile(job::GPUCompiler.CompilerJob)
    @ CUDA ~/.julia/dev/CUDA/src/compiler/execution.jl:317
  [7] cached_compilation(cache::Dict{UInt64, Any}, job::GPUCompiler.CompilerJob, compiler::typeof(CUDA.cufunction_compile), linker::typeof(CUDA.cufunction_link))
    @ GPUCompiler ~/.julia/dev/GPUCompiler/src/cache.jl:89
  [8] cufunction(f::GPUArrays.var"#53#54"{ComplexF16}, tt::Type{Tuple{CUDA.CuKernelContext, CuDeviceVector{ComplexF16, 1}, CuDeviceVector{NTuple{4, UInt32}, 1}}}; name::Nothing, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ CUDA ~/.julia/dev/CUDA/src/compiler/execution.jl:288
  [9] cufunction
    @ ~/.julia/dev/CUDA/src/compiler/execution.jl:282 [inlined]
 [10] macro expansion
    @ ~/.julia/dev/CUDA/src/compiler/execution.jl:102 [inlined]
 [11] #launch_heuristic#233
    @ ~/.julia/dev/CUDA/src/gpuarrays.jl:17 [inlined]
 [12] #gpu_call#1
    @ ~/.julia/dev/GPUArrays/src/device/execution.jl:68 [inlined]
 [13] gpu_call(::GPUArrays.var"#53#54"{ComplexF16}, ::CuArray{ComplexF16, 1, CUDA.Mem.DeviceBuffer}, ::CuArray{NTuple{4, UInt32}, 1, CUDA.Mem.DeviceBuffer})
    @ GPUArrays ~/.julia/dev/GPUArrays/src/device/execution.jl:48
 [14] rand!(rng::GPUArrays.RNG, A::CuArray{ComplexF16, 1, CUDA.Mem.DeviceBuffer})
    @ GPUArrays ~/.julia/dev/GPUArrays/src/host/random.jl:85
 [15] rand!(A::CuArray{ComplexF16, 1, CUDA.Mem.DeviceBuffer})
    @ CUDA ~/.julia/dev/CUDA/src/random.jl:129
 [16] rand(::Type, ::Int64)
    @ CUDA ~/.julia/dev/CUDA/src/random.jl:145
 [17] top-level scope
    @ REPL[4]:1
 [18] top-level scope
    @ ~/.julia/dev/CUDA/src/initialization.jl:65

julia> CUDA.rand(Int32, 3)
3-element CuArray{Int32, 1, CUDA.Mem.DeviceBuffer}:
   37399556
 1940475323
 -451007484

julia> CUDA.rand(Int8, 3)
3-element CuArray{Int8, 1, CUDA.Mem.DeviceBuffer}:
  11
 106
 113
```

### PR DESCRIPTION
**Pull request by maleadt**
Fixes https://github.com/JuliaGPU/CUDA.jl/issues/1081

### CODE REVIEW

**Comment by maleadt** [comment]
@bjarthur This should make the default RNG support Float16:

```julia
julia> CUDA.rand(Float16, 3)
3-element CuArray{Float16, 1, CUDA.Mem.DeviceBuffer}:
 0.416
 0.2705
 0.6924

julia> CUDA.rand(ComplexF16, 3)
3-element CuArray{ComplexF16, 1, CUDA.Mem.DeviceBuffer}:
   Float16(0.919) + Float16(0.671)im
 Float16(0.09863) + Float16(0.6377)im
    Float16(0.96) + Float16(0.546)im
```

**Comment by bjarthur** [comment]
and on the device to boot, right?

**Comment by maleadt** [comment]
Yes, we don't really have fallback functionality that doesn't run on the device (well, except for scalar indexing, but that complains pretty loudly).

**Comment by maleadt** [comment]
Also note that this new RNG is much faster than the old GPUArrays-based one:

```
julia> cuda_rng = CUDA.RNG();

julia> gpuarrays_rng = CUDA.GPUArrays.default_rng(CuArray);

julia> @benchmark CUDA.@sync rand!($cuda_rng, $a)
BenchmarkTools.Trial: 10000 samples with 1 evaluation.
 Range (min … max):  17.040 μs …  2.430 ms  ┊ GC (min … max): 0.00% … 99.04%
 Time  (median):     18.500 μs              ┊ GC (median):    0.00%
 Time  (mean ± σ):   20.604 μs ± 34.734 μs  ┊ GC (mean ± σ):  1.17% ±  0.99%

         ▃▆█▇▇▅▄▂▁                                             
  ▂▂▂▃▄▆███████████▇▆▆▅▅▄▄▄▃▃▃▃▃▃▃▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▂▂ ▄
  17 μs           Histogram: frequency by time        24.1 μs <

 Memory estimate: 2.34 KiB, allocs estimate: 71.

julia> @benchmark CUDA.@sync rand!($gpuarrays_rng, $a)
BenchmarkTools.Trial: 10000 samples with 1 evaluation.
 Range (min … max):  72.489 μs …  2.790 ms  ┊ GC (min … max): 0.00% … 98.44%
 Time  (median):     74.479 μs              ┊ GC (median):    0.00%
 Time  (mean ± σ):   81.211 μs ± 61.598 μs  ┊ GC (mean ± σ):  0.67% ±  1.40%

  █                                                           ▁
  █▆▃▁▃▃▅▆▅▁▁▁▁▁▃▁▁▁▁▁▁▁▁▁▁▁▄▆▁▁▁▁▁▁▁▁▄▄▃▄▃▁▁▁▁▁▁▁▁▁▃▃▄▆▄▁▄▃▆ █
  72.5 μs      Histogram: log(frequency) by time       443 μs <

 Memory estimate: 1.50 KiB, allocs estimate: 40.
```

and more correct:

```
julia> using RNGTest

julia> test_cuda_rng = RNGTest.wrap(cuda_rng, UInt32);

julia> test_gpuarrays_rng = RNGTest.wrap(gpuarrays_rng, UInt32);

julia> RNGTest.smallcrushTestU01(test_cuda_rng)

========= Summary results of SmallCrush =========

 Version:          TestU01 1.2.3
 Generator:        
 Number of statistics:  15
 Total CPU time:   00:00:07.71

 All tests were passed




julia> RNGTest.smallcrushTestU01(test_gpuarrays_rng)

========= Summary results of SmallCrush =========

 Version:          TestU01 1.2.3
 Generator:        
 Number of statistics:  15
 Total CPU time:   00:00:06.46
 The following tests gave p-values outside [0.001, 0.9990]:
 (eps  means a value < 1.0e-300):
 (eps1 means a value < 1.0e-15):

       Test                          p-value
 ----------------------------------------------
  1  BirthdaySpacings                 eps  
  2  Collision                        eps  
  3  Gap                              eps  
  4  SimpPoker                       1.0e-4
  5  CouponCollector                  eps  
  6  MaxOft                           eps  
  7  WeightDistrib                    eps  
 10  RandomWalk1 M                   6.0e-4
 ----------------------------------------------
 All other tests were passed
```

**Pull request merged**
