### PR TITLE
CuSparseArrayCSR (fixed cat ambiguitites from #1944)

### PR DESCRIPTION
**Pull request by nikopj**
fixed cat ambiguitites from #1944

### CODE REVIEW

**Comment by nikopj** [comment]
not sure what the build failures are from, seems unrelated to cusparse.

**Comment by maleadt** [comment]
Yeah, it's a race condition in GPUCompiler. Thanks for the fix!

**Comment by maleadt** [comment]
Hmm, implementing `Base._cat` isn't great though. Doesn't the ambiguity come from the zero-arg case? For that, wouldn't it be sufficient to do:

```julia
function Base.cat(A::CuSparseMatrixCSR, As::CuSparseMatrixCSR...; dims=3)
    As = (A, As...)
    # ...
end


function Base.cat(A::CuSparseArrayCSR, As::CuSparseArrayCSR...; dims=3)
    As = (A, As...)
    # ...
end
```

**Comment by maleadt** [comment]
Thanks!

**Pull request merged**
