### PR TITLE
Support view on unmanaged arrays.

### LINKED ISSUE #661: view causes KeyError in alias
The changes between CUDA.jl v2.0.2 and v2.1.0 have lead to some errors in the unit tests of ImplicitGlobalGrid.jl. The errors appear to be caused by the changes in CUDA.jl with respect to the support of views (@maleadt, [this PR](https://github.com/JuliaGPU/CUDA.jl/pull/472) is likely the reason). Here is the stacktrace of the reproduced error (using CUDA.jl v2.1.0):

```julia
julia> GG.cusendbuf_flat(n,dim,i,P)
ERROR: KeyError: key CuPtr{Nothing}(0x00002aaad797c050) not found
Stacktrace:
 [1] getindex at ./dict.jl:467 [inlined]
 [2] alias at /users/omlins/.julia/packages/CUDA/0p5fn/src/pool.jl:341 [inlined]
 [3] unsafe_contiguous_view at /users/omlins/.julia/packages/CUDA/0p5fn/src/array.jl:408 [inlined]
 [4] unsafe_view at /users/omlins/.julia/packages/CUDA/0p5fn/src/array.jl:403 [inlined]
 [5] view(::CuArray{Float64,1}, ::UnitRange{Int64}) at /users/omlins/.julia/packages/CUDA/0p5fn/src/array.jl:399
 [6] cusendbuf_flat(::Int64, ::Int64, ::Int64, ::CuArray{Float64,3}) at /users/omlins/.julia/dev/ImplicitGlobalGrid/src/update_halo.jl:233
 [7] top-level scope at REPL[30]:1
```

The function cusendbuf_flat is defined as follows

```julia
function cusendbuf_flat(n::Integer, dim::Integer, i::Integer, A::CuArray{T}) where T <: GGNumber
    return view(cusendbufs_raw[i][n]::CuVector{T},1:prod(halosize(dim,A)));
end
```
where cusendbufs_raw is of type `Array{Array{Any,1},1}` (defined in a let scope that includes `cusendbuf_flat` - this is to mimic C-like static variable behaviour).

Here is some output from the debugger, showing how we get to CuPtr{Nothing}(0x00002aaad797c050) :
```julia-repl
1|debug> fr
[1] unsafe_contiguous_view(a, I, dims) at /users/omlins/.julia/packages/CUDA/0p5fn/src/array.jl:405
  | a::CuArray{Float64,1} = <[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...>
  | I::Tuple{UnitRange{Int64}} = (1:30,)
  | dims::Tuple{Int64} = (30,)
  | offset::Int64 = 0
  | T::DataType = Float64
  | N::Int64 = 1
  | M::Int64 = 1
1|debug> st
In unsafe_contiguous_view(a, I, dims) at /users/omlins/.julia/packages/CUDA/0p5fn/src/array.jl:405
 405  @inline function unsafe_contiguous_view(a::CuArray{T}, I::NTuple{N,Base.ViewIndex}, dims::NTuple{M,Integer}) where {T,N,M}
 406      offset = Base.compute_offset1(a, 1, I) * sizeof(T)
 407  
>408      alias(a.baseptr)
 409      b = CuArray{T,M}(a.baseptr, dims, a.ctx; offset=a.offset+offset)
 410      finalizer(unsafe_free!, b)
 411      b.state = ARRAY_MANAGED
 412      return b
 413  end
About to run: <(getproperty)([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0...>
1|debug> s
In getproperty(x, f) at Base.jl:33
>33  getproperty(x, f::Symbol) = getfield(x, f)
About to run: <(getfield)([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...>
1|debug> nc
In getproperty(x, f) at Base.jl:33
>33  getproperty(x, f::Symbol) = getfield(x, f)
About to run: return CuPtr{Nothing}(0x00002aaae2eb6270)
1|debug> 
In unsafe_contiguous_view(a, I, dims) at /users/omlins/.julia/packages/CUDA/0p5fn/src/array.jl:405
 405  @inline function unsafe_contiguous_view(a::CuArray{T}, I::NTuple{N,Base.ViewIndex}, dims::NTuple{M,Integer}) where {T,N,M}
 406      offset = Base.compute_offset1(a, 1, I) * sizeof(T)
 407  
>408      alias(a.baseptr)
 409      b = CuArray{T,M}(a.baseptr, dims, a.ctx; offset=a.offset+offset)
 410      finalizer(unsafe_free!, b)
 411      b.state = ARRAY_MANAGED
 412      return b
 413  end
About to run: (CUDA.alias)(CuPtr{Nothing}(0x00002aaae2eb6270))
```
Then, some calls later it ends with:
```julia-repl
About to run: (rethrow)()
1|debug> 
ERROR: KeyError: key CuPtr{Nothing}(0x00002aaae2eb6270) not found
Stacktrace:
 [1] alias(::CuPtr{Nothing}) at /users/omlins/.julia/packages/CUDA/0p5fn/src/pool.jl:59
 [2] unsafe_contiguous_view(::CuArray{Float64,1}, ::Tuple{UnitRange{Int64}}, ::Tuple{Int64}) at /users/omlins/.julia/packages/CUDA/0p5fn/src/array.jl:408
 [3] unsafe_view(::CuArray{Float64,1}, ::Tuple{UnitRange{Int64}}, ::CUDA.Contiguous) at /users/omlins/.julia/packages/CUDA/0p5fn/src/array.jl:403
 [4] view(::CuArray{Float64,1}, ::Tuple{UnitRange{Int64}}) at /users/omlins/.julia/packages/CUDA/0p5fn/src/array.jl:399
 [5] cusendbuf_flat(::Int64, ::Int64, ::Int64, ::CuArray{Float64,3}) at /users/omlins/.julia/dev/ImplicitGlobalGrid
/src/update_halo.jl:232
 ```

### PR DESCRIPTION
**Pull request by maleadt**
Fixes https://github.com/JuliaGPU/CUDA.jl/issues/661

### CODE REVIEW

**Comment by maleadt** [comment]
@omlins Can you verify this PR fixes your issue?

**Comment by omlins** [comment]
@maleadt , I get the following error trying to install this version in an empty Julia 1.5 installation (no packages installed):
```julia
(@v1.5) pkg> add https://github.com/JuliaGPU/CUDA.jl/#326ee2c12fbf07d8b98bc9feb786a7b8ade0e612
    Cloning git-repo `https://github.com/JuliaGPU/CUDA.jl`
   Updating registry at `~/.julia/registries/General`
######################################################################## 100.0%
  Resolving package versions...
julia version requirement for package `CUDA [052768ef]` not satisfied
julia version requirement for package `CUDA [052768ef]` not satisfied
julia version requirement for package `CUDA [052768ef]` not satisfied
julia version requirement for package `CUDA [052768ef]` not satisfied
ERROR: Unsatisfiable requirements detected for package GPUCompiler [61eb1bfa]:
 GPUCompiler [61eb1bfa] log:
 ├─possible versions are: [0.1.0, 0.2.0, 0.3.0, 0.4.0-0.4.1, 0.5.0-0.5.5, 0.6.0-0.6.1, 0.7.0-0.7.3, 0.8.0-0.8.3, 0.9.0-0.9.1] or uninstalled
 ├─restricted to versions 0.9 by CUDA [052768ef], leaving only versions 0.9.0-0.9.1
 │ └─CUDA [052768ef] log:
 │   ├─possible versions are: 2.5.0 or uninstalled
 │   └─CUDA [052768ef] is fixed to version 2.5.0
 └─restricted by julia compatibility requirements to versions: [0.1.0, 0.2.0, 0.3.0, 0.4.0-0.4.1, 0.5.0-0.5.5, 0.6.0-0.6.1, 0.7.0-0.7.3, 0.8.0-0.8.3] or uninstalled — no versions left
 ```
 Is this because it requires Julia 1.6, or something else?

**Comment by maleadt** [comment]
`master` branch doesn't work on 1.5. You can back-port the change on the `compat` branch if you need 1.5.

**Comment by omlins** [comment]
I tried with Julia 1.6 and I can confirm that it works:
```julia
julia> using ImplicitGlobalGrid; GG = ImplicitGlobalGrid
[ Info: Precompiling ImplicitGlobalGrid [4d7a3746-15be-11ea-1130-334b0c4f5fa0]
┌ Warning: You appear to be using MPI.jl with the default MPI binary on a cluster.
│ We recommend using the system-provided MPI, see the Configuration section of the MPI.jl docs.
└ @ MPI ~/.julia/packages/MPI/b7MVG/deps/deps.jl:15
┌ Warning: You appear to be using MPI.jl with the default MPI binary on a cluster.
│ We recommend using the system-provided MPI, see the Configuration section of the MPI.jl docs.
└ @ MPI ~/.julia/packages/MPI/b7MVG/deps/deps.jl:15
ImplicitGlobalGrid

julia> import MPI

julia> using CUDA

julia> nx=7; ny=5; nz=6;

julia> MPI.Init();

julia> init_global_grid(nx, ny, nz, quiet=true, init_MPI=false);


julia> P = CUDA.ones(nx,  ny,  nz  );

julia> GG.allocate_bufs(P);

julia> dim=1; n=1; i=1;

julia> GG.cusendbuf_flat(n,dim,i,P)
30-element CuArray{Float32, 1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
```
Thanks a lot @maleadt !

**Comment by omlins** [comment]
Oh wait, maybe I was too fast. When I run again the unit tests it still produces some errors of which some show:
```julia
Got exception outside of a @test
  KeyError: key CuPtr{Nothing}(0x00002aaabaccb230) not found
```

**Comment by omlins** [comment]
It fails in `GG.cusendbuf(n,dim,i,P)` which does a reshape of the `cusendbuf_flat`, i.e. of the view...:
```julia
julia> GG.cusendbuf(n,dim,i,P)
ERROR: KeyError: key CuPtr{Nothing}(0x00002aaabd36e9c0) not found
Stacktrace:
 [1] getindex
   @ ./dict.jl:482 [inlined]
 [2] alias
   @ ~/.julia/packages/CUDA/9WiSQ/src/pool.jl:319 [inlined]
 [3] reshape(a::CuArray{Float64, 1}, dims::Tuple{Int64, Int64})
   @ CUDA ~/.julia/packages/CUDA/9WiSQ/src/array.jl:455
 [4] cusendbuf(n::Int64, dim::Int64, i::Int64, A::CuArray{Float64, 3})
   @ ImplicitGlobalGrid ~/.julia/dev/ImplicitGlobalGrid/src/update_halo.jl:243
 [5] top-level scope
   @ REPL[32]:1
   ```
The function `cusendbuf` does the following:
```julia
function cusendbuf(n::Integer, dim::Integer, i::Integer, A::CuArray{T}) where T <: GGNumber
    return reshape(cusendbuf_flat(n,dim,i,A), halosize(dim,A));
end
```

**Comment by maleadt** [comment]
Ah yes, needs the same for reshape and reinterpret. Please test again.

**Comment by omlins** [comment]
Yes, now it works with reshape:
```julia
julia> GG.cusendbuf(n,dim,i,P)
5×6 CuArray{Float32, 2}:
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
```
I could not test it with reinterpret as it fails to create CuArrays of type Float64: #664

**Comment by omlins** [comment]
OK, after installing the master branch of GPUCompiler it worked (allocate_bufs does a reinterpret of the Float64 buffer to Float32 buffer in this case - not a new allocation):
```julia
julia> P = CUDA.ones(Float64, nx,  ny,  nz  );

julia> GG.allocate_bufs(P);

julia> GG.cusendbuf(n,dim,i,P)
5×6 CuArray{Float64, 2}:
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0

julia> P = CUDA.ones(nx,  ny,  nz  );

julia> GG.allocate_bufs(P);

julia> GG.cusendbuf(n,dim,i,P)
5×6 CuArray{Float32, 2}:
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
```

**Comment by omlins** [comment]
Now all the unit tests pass - thanks @maleadt !

**Pull request merged**
