### PR TITLE
Don't collect `AbstractQ` objects in tests

### PR DESCRIPTION
**Pull request by dkarrasch**
This PR collects fixes to make CUDA.jl work properly with the new `AbstractQ` API.

### CODE REVIEW

**Comment by maleadt** [comment]
Thanks! I would have been happy to make these changes, just wanted to make sure I understood the intention.
Local testing revealed there's some other issues lurking though. Let's see what CI thinks.

**Comment by dkarrasch** [comment]
No worries. I'll just step through the issues as they arise. But feel free to speed up the process by pushing commits.

Yes, the intention was correct. The issue is that `Q`s are not stored in the matrix representation, so any iteration through the matrix coefficients requires to execute code (and potentially allocate memory etc.), so that was a poorly performing code pattern even before my Julia Base PR. And, in fact, part of the motivation was to reveal that code pattern by disallowing broadcasting and iteration on `AbstractQ` types.

**Comment by dkarrasch** [comment]
I think to fix the test on line 395 requires a new conversion method.

```julia
convert(::Type{T}, ::[QRPackedQ/AbstractQ?]) where {T<:CuArray} = lmul!(Q, T(I, size(Q))
```

that is multiplication of `Q` into the desired `CuArray` type?

**Comment by dkarrasch** [comment]
The challenge with the test is actually that there is only one path to materialize an `AbstractQ`, and a materialization is not readily available. So I wonder what we actually test when we compare two matrix representations. I think that would make more sense for a given, fixed matrix, and then we would compare with a fixed Q-matrix. I propose to compute `Q'Q` and compare to the identity matrix.

**Comment by maleadt** [comment]
I'm not sure what the exact intent of those tests is, as I didn't write them. Feel free to restructure them, or even change the wrappers (or suggest how to), as ultimately the goal of this functionality is compatibility with LinearAlgebra but using GPU types.

**Comment by dkarrasch** [comment]
https://github.com/JuliaLang/julia/pull/49424 should fix the remaining conversion issue.

**Comment by dkarrasch** [comment]
Now `nightly` is no longer failing, but timing out...

**Comment by maleadt** [comment]
Couldn't reproduce the hang locally, and seems to work on CI now too, so let's merge this. Thanks for looking into the failures!

**Pull request merged**
