### PR TITLE
CUSOLVER improvements

### PR DESCRIPTION
**Pull request by maleadt**
Adds `ldiv!` for QR from https://github.com/JuliaGPU/CUDA.jl/pull/1192, and implements `lu` fixing https://github.com/JuliaGPU/CUDA.jl/issues/1193.
cc @ChrisRackauckas

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
What about the `ldiv!` overloads for LU? Will those work as well?

**Comment by maleadt** [comment]
Not straight away. Looking into this, we'll have to duplicate all of `LinearAlgebra.LU` again into a CUDA-specific `CUDA.CuLU`, just like we had to do for `LinearAlgebra.QR`...

@andreasnoack would it be possible (without requiring a Julia 2.0-type API break) to make the Factorization classes GPU compatible using additional typevars for the pivot indices/coefficients/...? Those are currently all hard-coded to `Array`, which breaks GPU compatibility.

**Comment by andreasnoack** [comment]
It's a shame that we didn't finish that process before the Julia 1.0 release. Unfortunately, I'm not sure we'd be able to make that change without breaking things. We could try it and run PkgEval but I'd think that we'd see several errors. I have a vague memory of similar changes resulting in downstream failures in the past.

**Comment by maleadt** [comment]
Part of https://github.com/JuliaGPU/CUDA.jl/pull/1449

**Pull request closed without merging**
