### PR TITLE
Improvements to stream-ordered memory management

### PR DESCRIPTION
**Pull request by maleadt**

### CODE REVIEW

**Comment by danielwe** [comment]
This PR broke copying from unified memory to regular device memory, which my code used to do. Would it be a big hassle to resuscitate this functionality, or should I plan on doing things differently in the future? Was this safe to do in past versions?

**Comment by vchuravy** [comment]
Do you have an MWE of what you are doing?

**Comment by maleadt** [comment]
Please open a new issue with an MWE. CUDA.jl supports and tests copying to and from unified memory, so I doubt it's broken in generality.

**Comment by danielwe** [comment]
See #1263. I meant to post my original comment to #1176, sorry about the confusion.

**Pull request merged**
