### PR TITLE
Mark cublas version/handle as non-differentiable

### PR DESCRIPTION
**Pull request by wsmoses**
I'm working on getting a minimal working cublas AD working, but these are nevertheless prerequisites that will reduce the error log size for a lot of users already (e.g. https://github.com/EnzymeAD/Enzyme.jl/issues/1392)

### CODE REVIEW

**Review by vchuravy — APPROVED** [review]
Why does cudaconvert need a forward pass?

**Comment by wsmoses** [comment]
It needed one for the other PR to ensure unified memory setup is fine

**Comment by wsmoses** [comment]
@vchuravy can you merge?

**Comment by vchuravy** [comment]
> can you merge?

Yes, but there is a question how we test this code.

**Comment by wsmoses** [comment]
Yeah I have a test [just doing CUBLAS.Dot(x, y) but that presently fails for the reason of cudamemset as a fn not being found so we need to figure out the correct symbol materialization story. Still helpful for reducing error before then tho

**Pull request merged**
