### PR TITLE
Re-enable threading tests.

### PR DESCRIPTION
**Pull request by maleadt**

### CODE REVIEW

**Comment by maleadt** [comment]
Didn't see the illegal access failure, but one worker hanged in the threading tests. Now that we're not using spinlocks, at least aborting the process gives us a nice back-trace:

```
       From worker 2:	
      From worker 2:	signal (15): Terminated
      From worker 2:	in expression starting at /builds/JuliaGPU/CUDA.jl/test/threading.jl:25
      From worker 2:	clock_gettime at linux-vdso.so.1 (unknown line)
      From worker 2:	__clock_gettime at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
      From worker 2:	unknown function (ip: 0x7fada1efcbad)
      From worker 2:	unknown function (ip: 0x7fada1fd8da6)
      From worker 2:	unknown function (ip: 0x7fada1ffad18)
      From worker 2:	unknown function (ip: 0x7fada1ed2277)
      From worker 2:	unknown function (ip: 0x7fada1dd6b01)
      From worker 2:	unknown function (ip: 0x7fada1dd8c73)
      From worker 2:	cuMemcpyDtoH_v2 at /usr/lib/x86_64-linux-gnu/libcuda.so (unknown line)
      From worker 2:	macro expansion at /builds/JuliaGPU/CUDA.jl/lib/cuda/libcuda.jl:503 [inlined]
      From worker 2:	macro expansion at /builds/JuliaGPU/CUDA.jl/lib/cuda/error.jl:108 [inlined]
      From worker 2:	cuMemcpyDtoH_v2 at /builds/JuliaGPU/CUDA.jl/lib/utils/call.jl:93
      From worker 2:	#unsafe_copyto!#6 at /builds/JuliaGPU/CUDA.jl/lib/cuda/memory.jl:324 [inlined]
      From worker 2:	unsafe_copyto! at /builds/JuliaGPU/CUDA.jl/lib/cuda/memory.jl:317 [inlined]
      From worker 2:	unsafe_copyto! at /builds/JuliaGPU/CUDA.jl/src/array.jl:309 [inlined]
      From worker 2:	copyto! at /builds/JuliaGPU/CUDA.jl/src/array.jl:284
      From worker 2:	copyto! at /builds/JuliaGPU/CUDA.jl/.julia/packages/GPUArrays/HGtNV/src/host/abstractarray.jl:112 [inlined]
      From worker 2:	Array at ./array.jl:541 [inlined]
      From worker 2:	Array at ./boot.jl:429
      From worker 2:	_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2145 [inlined]
      From worker 2:	jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2323
      From worker 2:	macro expansion at /builds/JuliaGPU/CUDA.jl/test/threading.jl:37 [inlined]
      From worker 2:	#2552#threadsfor_fun at ./threadingconstructs.jl:61
      From worker 2:	#2552#threadsfor_fun at ./threadingconstructs.jl:28
      From worker 2:	_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2145 [inlined]
      From worker 2:	jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2323
      From worker 2:	jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1700 [inlined]
      From worker 2:	start_task at /buildworker/worker/package_linux64/build/src/task.c:687
      From worker 2:	unknown function (ip: (nil))
      From worker 2:	unknown function (ip: (nil))


      From worker 2:	_mm_pause at /usr/local/lib/gcc/x86_64-pc-linux-gnu/7.3.0/include/xmmintrin.h:1267 [inlined]
      From worker 2:	jl_gc_wait_for_the_world at /buildworker/worker/package_linux64/build/src/gc.c:205 [inlined]
      From worker 2:	jl_gc_collect at /buildworker/worker/package_linux64/build/src/gc.c:3099
      From worker 2:	gc at ./gcutils.jl:68 [inlined]
      From worker 2:	scan at /builds/JuliaGPU/CUDA.jl/src/memory/binned.jl:105
      From worker 2:	macro expansion at /builds/JuliaGPU/CUDA.jl/src/memory/binned.jl:366 [inlined]
      From worker 2:	macro expansion at /builds/JuliaGPU/CUDA.jl/.julia/packages/TimerOutputs/NvIUx/src/TimerOutput.jl:245 [inlined]
      From worker 2:	macro expansion at /builds/JuliaGPU/CUDA.jl/src/memory/binned.jl:365 [inlined]
      From worker 2:	#4 at ./task.jl:358
      From worker 2:	_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2159 [inlined]
      From worker 2:	jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2323
      From worker 2:	jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1700 [inlined]
      From worker 2:	start_task at /buildworker/worker/package_linux64/build/src/task.c:687
      From worker 2:	unknown function (ip: (nil))
      From worker 2:	unknown function (ip: (nil))
      From worker 2:	Allocations: 571282176 (Pool: 571133611; Big: 148565); GC: 526
      From worker 2:	
      From worker 2:	signal (6): Aborted
      From worker 2:	in expression starting at /builds/JuliaGPU/CUDA.jl/test/threading.jl:25
      From worker 2:	clock_gettime at linux-vdso.so.1 (unknown line)
      From worker 2:	__clock_gettime at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
      From worker 2:	unknown function (ip: 0x7fada1efcbad)
      From worker 2:	unknown function (ip: 0x7fada1fd8da6)
      From worker 2:	unknown function (ip: 0x7fada1ffad18)
      From worker 2:	unknown function (ip: 0x7fada1ed2277)
      From worker 2:	unknown function (ip: 0x7fada1dd6b01)
      From worker 2:	unknown function (ip: 0x7fada1dd8c73)
      From worker 2:	cuMemcpyDtoH_v2 at /usr/lib/x86_64-linux-gnu/libcuda.so (unknown line)
      From worker 2:	macro expansion at /builds/JuliaGPU/CUDA.jl/lib/cuda/libcuda.jl:503 [inlined]
      From worker 2:	macro expansion at /builds/JuliaGPU/CUDA.jl/lib/cuda/error.jl:108 [inlined]
      From worker 2:	cuMemcpyDtoH_v2 at /builds/JuliaGPU/CUDA.jl/lib/utils/call.jl:93
      From worker 2:	#unsafe_copyto!#6 at /builds/JuliaGPU/CUDA.jl/lib/cuda/memory.jl:324 [inlined]
      From worker 2:	unsafe_copyto! at /builds/JuliaGPU/CUDA.jl/lib/cuda/memory.jl:317 [inlined]
      From worker 2:	unsafe_copyto! at /builds/JuliaGPU/CUDA.jl/src/array.jl:309 [inlined]
      From worker 2:	copyto! at /builds/JuliaGPU/CUDA.jl/src/array.jl:284
      From worker 2:	copyto! at /builds/JuliaGPU/CUDA.jl/.julia/packages/GPUArrays/HGtNV/src/host/abstractarray.jl:112 [inlined]
      From worker 2:	Array at ./array.jl:541 [inlined]
      From worker 2:	Array at ./boot.jl:429
      From worker 2:	_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2145 [inlined]
      From worker 2:	jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2323
      From worker 2:	macro expansion at /builds/JuliaGPU/CUDA.jl/test/threading.jl:37 [inlined]
      From worker 2:	#2552#threadsfor_fun at ./threadingconstructs.jl:61
      From worker 2:	#2552#threadsfor_fun at ./threadingconstructs.jl:28
      From worker 2:	_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2145 [inlined]
      From worker 2:	jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2323
      From worker 2:	jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1700 [inlined]
      From worker 2:	start_task at /buildworker/worker/package_linux64/build/src/task.c:687
      From worker 2:	unknown function (ip: (nil))
      From worker 2:	unknown function (ip: (nil))

      
      From worker 2:	jl_safepoint_wait_gc at /buildworker/worker/package_linux64/build/src/safepoint.c:157
      From worker 2:	_IO_funlockfile at /lib/x86_64-linux-gnu/libpthread.so.0 (unknown line)
      From worker 2:	unknown function (ip: 0xa0)
      From worker 2:	unknown function (ip: (nil))
      From worker 2:	Allocations: 571282176 (Pool: 571133611; Big: 148565); GC: 526
```

Soo... a hang in CUDA?

**Comment by maleadt** [comment]
Added what might be a fix for https://github.com/JuliaGPU/CUDA.jl/issues/254. Unsure about it though, and also encountered a concurrency violation during execution of a finalizer in the threading tests...

**Comment by maleadt** [comment]
@kshyatt maybe you could give this a spin with your threading app too?

**Comment by IanButterworth** [comment]
I'm seeing #254 in a threaded setup, now we've moved to CUDA.jl. 

What't the current thinking on this PR? Also are the conflicts here easily resolve-able? 

Otherwise I can try to de-thread the CUDA usage.

**Comment by maleadt** [comment]
> What't the current thinking on this PR? Also are the conflicts here easily resolve-able?

This PR should be good to go, but I don't have good threading use cases. So if you could test it out and report back, that would be very useful.

I'll see about rebasing this.

**Comment by IanButterworth** [comment]
Just got around to testing this a few times in the wild and no errors. Thanks!

**Comment by IanButterworth** [comment]
It'd be helpful if this could be merged and released 🙏

**Comment by maleadt** [comment]
OK, let's merge this. I prefer to have it on master for a couple of days though, to see if there aren't any spurious threading-related issues.

**Comment by IanButterworth** [comment]
Sounds good, thanks

**Pull request merged**
