### PR TITLE
Enzyme: Forward mode sync

### PR DESCRIPTION
**Pull request by wsmoses**
@vchuravy for fixing https://buildkite.com/julialang/kernelabstractions-dot-jl/builds/931#018f654d-0616-4d67-8089-c01729873000

### CODE REVIEW

**Comment by vchuravy** [comment]
```
Error in testset libraries/enzyme:
Test Failed at /var/lib/buildkite-agent/builds/gpuci-16/julialang/cuda-dot-jl/test/libraries/enzyme.jl:27
  Expression: all(dA .≈ 2:2:128)
Error in testset libraries/enzyme:
Error During Test at /var/lib/buildkite-agent/builds/gpuci-16/julialang/cuda-dot-jl/test/setup.jl:62
  Got exception outside of a @test
  LoadError: UndefVarError: batch_width not defined
  Stacktrace:
```

**Comment by maleadt** [comment]
Let's mark this as draft to save on CI resources until tests initially pass.

**Comment by wsmoses** [comment]
@maleadt okay I fixed the minor typos that hopefully should let it pass.

Assuming it passes, does it look good to you?

**Comment by wsmoses** [comment]
@maleadt admittedly this is a bit greedy of a request, but would it be possible to release (perhaps via backport since I know you're working on some breaking changes) the current EnzymeCUDA functionality.

This in particular is needed to re-fix KA+Enzyme CI [and other downstream ML users would like].

**Comment by maleadt** [comment]
I'd rather let the master branch bake for a while more. Can you create a PR against https://github.com/JuliaGPU/CUDA.jl/tree/release-5.3 with the commits (`git cherry-pick ...`) you need?

**Comment by maleadt** [comment]
@wsmoses: https://github.com/JuliaRegistries/General/pull/106889

**Pull request merged**
