### PR TITLE
@atomic support * and /

### PR DESCRIPTION
**Pull request by yuehhua**
Need this to avoid unsupported dynamic function call compile error in FluxML/NNlibCUDA.jl#1

### CODE REVIEW

**Comment by maleadt** [comment]
Thanks. Could you add some tests here: https://github.com/JuliaGPU/CUDA.jl/blob/632f960a332f57aa8b885e39ab6fb7850e6a3bf5/test/device/intrinsics.jl#L1023

**Comment by yuehhua** [comment]
Currently, I tests over `@atomic` on `*` and `/`. But it seems available for `Float32` only. Do we have chance to support `Int32`, `Int64`, or even `UInt` series?

**Comment by yuehhua** [comment]
CI fails on `sorting                               (6) |         failed at 2021-04-17T21:31:21.390` with error message:

```julia
Some tests did not pass: 126 passed, 1 failed, 0 errored, 0 broken.
--
  | sorting: Test Failed at /var/lib/buildkite-agent/builds/rtx2080-hydor-elis-ugent-be/julialang/cuda-dot-jl/test/sorting.jl:256
  | Expression: check_sort!(Float32, (4, 100000); by = (x->begin
  | abs(x - 0.5)
  | end), dims = 2)
```

It seems unrelated to this PR.

**Comment by xaellison** [comment]
@yuehhua I believe/hope that sorting error will be fixed by #845

**Comment by yuehhua** [comment]
@maleadt Is this ready to go?

**Comment by maleadt** [comment]
Yeah, good to go. This could be extended to other types though; it uses `atomic_cas` anyway as there's no native atomic multiplication, so that could be extended to deal with any other type that can be compare-and-swapped.

**Pull request merged**
