### PR TITLE
Rework memoization

### PR DESCRIPTION
**Pull request by maleadt**
We've had some issues with both Memoize.jl and Memoization.jl, and even though @marius311 has been quick to fix them, performance also isn't too great (at least, not when using a thread-safe dictionary). So instead I'm trying to roll my own simple, no-frills, lockless (but thread-safe) `@memoize` macro for use in CUDA.jl.

### CODE REVIEW

**Comment by marius311** [comment]
If you have time, out of curiousity, can you describe the performance requirements? I've been kind of obsessed with making Memoization as fast as possible while retaining flexibility. With the default IdDict which is what it seemed like you were using before, I think it (like Memoize, or a hand-rolled `const cache` lookup) generates essentially optimal code. I haven't tested performance with ThreadSafeDicts, I guess thats the issue? And if I'm reading this PR right, you decided to go with a thread-local cache?

**Comment by maleadt** [comment]
There's a couple of things:
- IdDict is slower than regular Dict for the kind of lookups I was considering (4ns instead of 12ns or so)
- when there's no arguments to key the cache with, I decided to memoize using a Ref, bringing the time of access further down to 2ns or so

However, with CUDA.jl I greatly care about thread safety. Just using a ThreadSafeDict just puts a lock in there, and even with a SpinLock that takes 10s of ns extra. Instead, I decided to use a per-thread cache that doesn't need any lock to access. It only needs to be initialized once, but that can be done by one selected thread using an atomic CAS.

All that gives me a thread-safe memoization whose happy path only takes ~5ns or so, which is pretty great. I wanted to use for caching frequently-called version getters that ordinarily take a couple of 10s of ns, so performance requirements were high.

**Comment by marius311** [comment]
Interesting, thanks. Sounds like if Memoization had:

* Something like `@memoize ThreadLocal(Dict) foo(x) ...` for an appropriately written `ThreadLocal` function, and
* Something like `@memoize Ref foo() ...` for arg-less functions

that'd get it on par with the performance of your version. Despite getting dropped as a CUDA dep, I think both of these would be nice additions to Memoization anyway, will work on this.

**Comment by maleadt** [comment]
Here's a prototype of such a ThreadSafe wrapper:

```julia
@inline assume(cond::Bool) = Base.llvmcall(("""
        declare void @llvm.assume(i1)

        define void @entry(i8) #0 {
            %cond = icmp eq i8 %0, 1
            call void @llvm.assume(i1 %cond)
            ret void
        }

        attributes #0 = { alwaysinline }""", "entry"),
    Nothing, Tuple{Bool}, cond)

"""
    ThreadSafe{T}() do
        # initialization, producing a value of type T
    end

A thread-safe wrapper around a value of type `T`. Fetch the value by calling `getindex`. The
constructor is ensured to only be called once from a single thread.

This type is intended for lazy initialization of e.g. global structures, without using
`__init__`. It is similar to protecting accesses using a lock, but is much cheaper.

"""
struct ThreadSafe{T,F}
    # 0: uninitialized
    # 1: initializing
    # 2: initialized
    guard::Threads.Atomic{Int}
    value::Base.RefValue{T}
    constructor::F

    ThreadSafe{T,F}(constructor::F) where {T,F} =
        new(Threads.Atomic{Int}(0), Ref{T}(), constructor)
end
ThreadSafe{T}(constructor::F) where {T,F} = ThreadSafe{T,F}(constructor)

function Base.getindex(x::ThreadSafe)
    while x.guard[] != 2
        initialize!(x)
    end
    assume(isassigned(x.value)) # to get rid of the check
    x.value[]
end

@noinline function initialize!(x::ThreadSafe)
    status = Threads.atomic_cas!(x.guard, 0, 1)
    if status == 0
        x.value[] = x.constructor()
        x.guard[] = 2
    else
        ccall(:jl_cpu_pause, Cvoid, ())
        # Temporary solution before we have gc transition support in codegen.
        ccall(:jl_gc_safepoint, Cvoid, ())

        # should we `yield()` here instead?
    end
    return
end


## demo

const per_thread = ThreadSafe{Vector{Int}}() do
    [42 for _ in 1:Threads.nthreads()]
end

function main()
    x = per_thread[]

    @show x
end

isinteractive() || main()
```

I'm not entirely sure this is correct -- I'm no multithreading guru -- but it seems to work well.

**Comment by vchuravy** [comment]
`        # should we `yield()` here instead?`

See my comment in: https://github.com/JuliaGPU/CUDA.jl/pull/993#discussion_r653905036
You can have a concurrency bug here which will manifest itself as a live-lock. (Having written to many of those myself.)

**Comment by maleadt** [comment]
#993 replaces that part, so only needs a fix there

**Pull request merged**
