### PR TITLE
Update `CUSPARSE.sum_dim<n>` to allow for arbitrary function on elements

### LINKED ISSUE #1406: CUSPARSE does not support reductions
On master, even the simplest reduction fails:
```julia
julia> using CUDA, CUDA.CUSPARSE, Random, SparseArrays

julia> x = sprand(3, 3, 0.5) |> CuSparseMatrixCSR
3×3 CuSparseMatrixCSR{Float64, Int32} with 4 stored entries:
  ⋅                  0.33280841492717694   ⋅ 
 0.2627012132720039  0.2749904007443871    ⋅ 
  ⋅                   ⋅                   0.009417688176282524

julia> sum(x)
ERROR: Scalar indexing is disallowed.
Invocation of getindex resulted in scalar indexing of a GPU array.
This is typically caused by calling an iterating implementation of a method.
Such implementations *do not* execute on the GPU, but very slowly on the CPU,
and therefore are only permitted from the REPL for prototyping purposes.
If you did intend to index this array, annotate the caller with @allowscalar.
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:33
  [2] assertscalar(op::String)
    @ GPUArrays ~/.julia/packages/GPUArrays/umZob/src/host/indexing.jl:53
  [3] getindex(xs::CuArray{Int32, 1, CUDA.Mem.DeviceBuffer}, I::Int64)
    @ GPUArrays ~/.julia/packages/GPUArrays/umZob/src/host/indexing.jl:86
  [4] getindex(A::CuSparseMatrixCSR{Float64, Int32}, i0::Int64, i1::Int64)
    @ CUDA.CUSPARSE ~/.julia/packages/CUDA/BJT41/lib/cusparse/array.jl:312
  [5] _getindex
    @ ./abstractarray.jl:1262 [inlined]
  [6] getindex
    @ ./abstractarray.jl:1218 [inlined]
  [7] iterate
    @ ./abstractarray.jl:1144 [inlined]
  [8] iterate
    @ ./abstractarray.jl:1142 [inlined]
  [9] _foldl_impl
    @ ./reduce.jl:56 [inlined]
 [10] foldl_impl(op::Base.BottomRF{typeof(Base.add_sum)}, nt::Base._InitialValue, itr::CuSparseMatrixCSR{Float64, Int32})
    @ Base ./reduce.jl:48
 [11] mapfoldl_impl
    @ ./reduce.jl:44 [inlined]
 [12] #mapfoldl#244
    @ ./reduce.jl:162 [inlined]
 [13] mapfoldl
    @ ./reduce.jl:162 [inlined]
 [14] _mapreduce
    @ ./reduce.jl:423 [inlined]
 [15] _mapreduce_dim
    @ ./reducedim.jl:330 [inlined]
 [16] #mapreduce#725
    @ ./reducedim.jl:322 [inlined]
 [17] mapreduce
    @ ./reducedim.jl:322 [inlined]
 [18] #_sum#735
    @ ./reducedim.jl:894 [inlined]
 [19] _sum
    @ ./reducedim.jl:894 [inlined]
 [20] #_sum#734
    @ ./reducedim.jl:893 [inlined]
 [21] _sum
    @ ./reducedim.jl:893 [inlined]
 [22] #sum#732
    @ ./reducedim.jl:889 [inlined]
 [23] sum(a::CuSparseMatrixCSR{Float64, Int32})
    @ Base ./reducedim.jl:889
 [24] top-level scope
    @ REPL[49]:1
 [25] top-level scope
    @ ~/.julia/packages/CUDA/BJT41/src/initialization.jl:52
```
I get a similar errors with `CuSparseMatrixCSC` and `sum(x; dims=1)`.

### LINKED ISSUE #1983: `CUSPARSE.sum_dim1` sums the absolute values of elements
Both functions `sum_dim1` and `sum_dim2` calculate the sums of absolute values of appropriate elements. Is this by design? If this is the case maybe the name should be changed?

### PR DESCRIPTION
**Pull request by lpawela**
This fixes #1983 

EDIT: also fixes https://github.com/JuliaGPU/CUDA.jl/issues/1406

### CODE REVIEW

**Comment by maleadt** [comment]
`sum_dim1` etc aren't public functions, so I don't see why we would want to add configurability without a public API to use it.

Why are you calling these functions directly?

**Comment by lpawela** [comment]
The main reason is scalar indexing when using `sum(ad, dims=2)`

```julia
julia> using CUDA, SparseArrays

julia> a = sprand(10, 10, 0.1);

julia> ad = CUDA.CUSPARSE.CuSparseMatrixCSR(a);

julia> sum(ad, dims=2)
┌ Warning: Performing scalar indexing on task Task (runnable) @0x00007f2882ffc010.
│ Invocation of getindex resulted in scalar indexing of a GPU array.
│ This is typically caused by calling an iterating implementation of a method.
│ Such implementations *do not* execute on the GPU, but very slowly on the CPU,
│ and therefore are only permitted from the REPL for prototyping purposes.
│ If you did intend to index this array, annotate the caller with @allowscalar.
└ @ GPUArraysCore ~/.julia/packages/GPUArraysCore/uOYfN/src/GPUArraysCore.jl:106
10×1 Matrix{Float64}:
 0.7312257183333077
 0.2736255562180383
 0.0
 0.8569093552724679
 0.24512118904635305
 0.0
 0.0
 0.0
 0.0
 0.9815900426493798
```

**Comment by maleadt** [comment]
Right, but then we should hook up `sum` to these functions so that you don't have to rely on internals.

**Comment by lpawela** [comment]
I just noticed that the `sum_dim1` and `sum_dim2` seem to be inverted compared to `Base.sum`

```julia
julia> using CUDA, SparseArrays

julia> A = sprand(4, 4, 0.8);

julia> dA = CUDA.CUSPARSE.CuSparseMatrixCSR(A);

julia> CUDA.CUSPARSE.sum_dim1(dA)
4-element CuArray{Float64, 1, CUDA.Mem.DeviceBuffer}:
 2.2032459284126857
 1.2487818875938437
 0.7308272178094658
 1.9313369732308794

julia> sum(A, dims=1)
1×4 Matrix{Float64}:
 1.40888  1.72323  0.602062  2.38003

julia> sum(A, dims=2)
4×1 Matrix{Float64}:
 2.2032459284126857
 1.2487818875938437
 0.7308272178094658
 1.9313369732308794
```
All my previous inputs were symmetric, so it didn't show. Am I missing something or is this a bug?

**Comment by maleadt** [comment]
Yeah, looks like the functions are named incorrectly.

**Comment by maleadt** [comment]
Hmm, I still don't like this. Those internal functions aren't meant to be reused. As I mention, this should be implemented as `Base.sum`.

I've tried something like that, reusing the device iterators we have for the native broadcast. As a result, this now supports most of `mapreduce`, including a full reduction. Could still be improved, of course (e.g., adding in-place support, generalizing how it handles `dims`, etc).

**Pull request merged**
