### PR TITLE
ae/partialsort

### LINKED ISSUE #93: GPU Implementation of partialsort!
It would be great if there was an implementation of sort! and partialsort! for CuArrays.

A simple (1D array, radix-2) native Julia implementation would be really helpful as a good starting point.

Other issues have considered wrapping Thrust or CUB JuliaGPU/CuArrays.jl#525.

This should enable a number of higher level functions, such as the ability to generate statistics about data (median, quartiles, etc) on the GPU. 

A few (possibly) helpful links:
https://www.cse.chalmers.se/~tsigas/papers/GPU-Quicksort-jea.pdf
https://onlinelibrary.wiley.com/doi/full/10.1002/cpe.3611
https://sourceforge.net/projects/cuda-quicksort/

### PR DESCRIPTION
**Pull request by xaellison**
`partialsort` and `partialsort!` for CuArrays. Should cover all cases that Base covers for Arrays.

Eg:
```
using AbstractPlotting, Makie, CUDA
a = rand(Float32, 40000)
c = CuArray(a)
partialsort!(c, 1:1000)
lines(c)
```

image

### CODE REVIEW

**Comment by xaellison** [comment]
@maleadt ci failures unrelated I think

**Comment by maleadt** [comment]
@xaellison Good to go?

**Comment by xaellison** [comment]
Yeah let's ship it

**Comment by maleadt** [comment]
Great stuff, thanks!

**Pull request merged**
