### PR TITLE
Added documentation for CUDA installation

### LINKED ISSUE #1: Documentation: installation instructions
Information on how to install CUDA, troubleshoot common problems, make sure Julia CUDA works, etc.

### PR DESCRIPTION
**Pull request by dnabanita7**
Fix #1 I have added the documentation specifically for Ubuntu and tried to keep it more general.

### CODE REVIEW

**Comment by maleadt** [comment]
Thanks! Most of that seems inspired by https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html? Maybe it's better to just link then. I personally don't feel comfortable putting such specific installation instructions here. Furthermore, it's actually "not recommended" to install CUDA that way on Ubuntu (or many Linux distributions for that matter), and you should probably use distribution-specific packages instead.

I was rather imagining some more high-level instructions:
- explain how there's two parts to install, the NVIDIA driver and the CUDA toolkit
- does `lsmod` show `nvidia`? if not, you need the NVIDIA driver; refer to X or Y for more details.
- maybe some information on how there's both distribution-provided packages, and the NVIDIA installer, and why the former is preferred
- does `lsmod` show nvidia? try `nvidia-smi` to see if your GPU is detected
- if not, you might need a different driver, check `dmesg`
- do you have `nvcc`/`ptxas`/`nvobjdump`? if not, you need to install the CUDA toolkit.
- if you have everything but Julia/CUDA does not work, try compiling a CUDA C hello world file and execute it
- maybe some HPC specific instructions, where you won't be able to install CUDA but will need to `module load`

**Comment by dnabanita7** [comment]
Ok then I will add these. I think the above mentioned questions almost summarizes everything. Shall I link the cuda docs and delete these extra paragraphs?

**Comment by Naba7** [comment]
>  Furthermore, it's actually "not recommended" to install CUDA that way on Ubuntu (or many Linux distributions for that matter), and you should probably use distribution-specific packages instead.

I thought that but then I was confused what you actually wanted.

**Comment by dnabanita7** [comment]
>  if not, you need the NVIDIA driver; refer to X or Y for more details.

I am not sure if I understand this properly. `lsmod` enlists all the loaded kernel modules while `modprobe` sometimes shows the mentioned error.

**Comment by maleadt** [comment]
I went with a more simplified set of instructions in https://github.com/JuliaGPU/CUDA.jl/commit/86dc93d387aeef89241dba90bf93602fe9e188cc -- it think it would be confusing if we elaborate too much, e.g., including sbatch snippets or information on the compilation flow. Feel free to add more details if you think they are useful!

**Pull request closed without merging**
