### PR TITLE
Use type symbols to generate wrapper methods

### PR DESCRIPTION
**Pull request by martenlienen**
I noticed these typos in the meta programming code that generates the wrappers for CUSOLVER.

### CODE REVIEW

**Comment by martenlienen** [comment]
Is the test pipeline broken? I would think that this PR is unrelated to CUPTI being unavailable.

**Comment by maleadt** [comment]
It was, I fixed it and rebased this PR.

**Comment by martenlienen** [comment]
Something is not quite right in the documentation setup even though it worked in #532

**Comment by martenlienen** [comment]
Yes, finally all green :)

**Comment by maleadt** [comment]
Great, thanks!

**Pull request merged**
