### PR TITLE
Add Enzyme to test dependencies

### PR DESCRIPTION
**Pull request by vchuravy**
For https://github.com/JuliaGPU/KernelAbstractions.jl/pull/382

### CODE REVIEW

**Comment by vchuravy** [comment]
@wsmoses one challenge here is that this causes CUDA and Enzyme to be tightly coupled via CI and Enzyme.jl tends to lag a bit behind in LLVM and GPUCompiler uptakes...

RN this means that https://github.com/JuliaGPU/KernelAbstractions.jl/pull/382 has not been tested on any of KAs GPU backend and I don't think we can add it as a test-dependency to CUDA.jl

Not sure what the right solution here is, maybe a special CI job on KA that installs both Enzyme and CUDA? @maleadt any thoughts?

**Comment by vchuravy** [comment]
Of course the same issue comes up in https://github.com/JuliaGPU/CUDA.jl/pull/1869

**Comment by wsmoses** [comment]
We do try to stay as up to date as possible, and have kept up fast historically, but the recent breaking changes (specifically the LLVM context change) has been particularly troublesome to change everywhere...

**Comment by maleadt** [comment]
I don't think Enzyme as a test dep is great, because of the aforementioned compatibility issues. Maybe we could hack it in though, as a special testset that requires additional dependencies (installed by CI, with the ability to ignore installation failures like we do on GPUCompiler.jl).

Or maybe this could go into the tests of the extension package that https://github.com/JuliaGPU/CUDA.jl/pull/1869 should add? (Can extension packages even have tests?)

**Pull request closed without merging**
