### PR TITLE
Add and fix some aqua tests

### LINKED ISSUE #1964: Add aqua tests
I recently loaded RRTMGP and came across several warnings:

```julia
julia> using RRTMGP
[ Info: Precompiling RRTMGP [a01a1ee8-cea4-48fc-987c-fc7878d79da1]
WARNING: method definition for attribute at /Users/charliekawczynski/.julia/packages/CUDA/DfvRa/lib/cudadrv/pool.jl:79 declares type variable T but does not use it.
WARNING: method definition for attribute! at /Users/charliekawczynski/.julia/packages/CUDA/DfvRa/lib/cudadrv/pool.jl:90 declares type variable T but does not use it.
WARNING: method definition for #cudacall#42 at /Users/charliekawczynski/.julia/packages/CUDA/DfvRa/lib/cudadrv/execution.jl:131 declares type variable N but does not use it.
WARNING: method definition for #bitonic_sort!#3 at /Users/charliekawczynski/.julia/packages/CUDA/DfvRa/src/sorting.jl:836 declares type variable T but does not use it.
```

Perhaps this is an old version of CUDA, but we should add aqua tests to prevent these warnings from cropping up in the first place.

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR adds and fixes some aqua tests. Closes #1964.

### CODE REVIEW

**Comment by maleadt** [comment]
Can you explain why some of these changes are necessary? They only seem to add duplicate definitions with manually-split type signatures, which doesn't seem great.

**Comment by charleskawczynski** [comment]
> Can you explain why some of these changes are necessary? They only seem to add duplicate definitions with manually-split type signatures, which doesn't seem great.

Sure, here's an explanation based on my best understanding. Let's take this fix as an example:

master
```julia
LinearAlgebra.triu(A::Union{$SparseMatrixType{T,M}, Transpose{T,<:$SparseMatrixType}, Adjoint{T,<:$SparseMatrixType}}) where {T,M} = 
    $SparseMatrixType( triu(CuSparseMatrixCOO(A), 0) )
```

fix
```julia
LinearAlgebra.triu(A::$SparseMatrixType{T,M}) where {T,M} = 
    $SparseMatrixType( triu(CuSparseMatrixCOO(A), 0) )
LinearAlgebra.triu(A::Union{Transpose{T,<:$SparseMatrixType}, Adjoint{T,<:$SparseMatrixType}}) where {T} = 
    $SparseMatrixType( triu(CuSparseMatrixCOO(A), 0) )
```

In the main commit, Julia creates methods for each element of the `Union`. In the case of the second element, the created method is:

```julia
LinearAlgebra.triu(A::Transpose{T,<:$SparseMatrixType) where {T,M} = 
    $SparseMatrixType( triu(CuSparseMatrixCOO(A), 0) )
```

In this method definition, type `M` is unused and may suffer from https://github.com/JuliaLang/julia/issues/29393. In the fix, the first method was separated into a separate method, but only with the type parameters that are used, so it has no unbound arguments. The second method definition omits the type parameter `M`, so it too excludes unbound type arguments.

I apologize about the duplication, I tried my best to keep duplication minimal (e.g., creating a shared `_unsafe_wrapped_buff` from `unsafe_wrap`). I'm not sure there's alternatives to fix these issues, unfortunately. Perhaps we could ask for https://github.com/JuliaLang/julia/issues/29393 to be reopened, since the issue was closed but technically remains an issue?

**Comment by maleadt** [comment]
OK thanks, that clears it up. Pushed some additional things, this should be good to go if CI agrees.

**Comment by charleskawczynski** [comment]
Thanks!

**Pull request merged**
