### PR TITLE
Adapt to JuliaLang/julia#38487.

### PR DESCRIPTION
**Pull request by maleadt**

### CODE REVIEW

**Comment by maleadt** [comment]
Annoying how the threading test doesn't fail after removing the protections (but without the PR in Julia being merged)... Maybe now we `device_reset!` at the beginning of every test there isn't enough memory pressure.

**Comment by maleadt** [comment]
Benchmarks caught it!

```
WARNING: Error while freeing CuPtr{Nothing}(0x00007fff63d8b600):
AssertionError(msg="!(islocked(nrl.rl)) || nrl.rl.locked_by !== current_task()")
```

**Comment by vchuravy** [comment]
We still need the `@spinlock`? Maybe worth adding to Julia base?

**Comment by maleadt** [comment]
> We still need the `@spinlock`?

I think so. We can't `wait` from within a finalizer, because that would cause a task switch. So if another thread is in `free` (which can happen from non-finalizer code because of `unsafe_free`) we just need to wait until that's done. So we spin.

This seems pretty specific, so I'm not sure it's useful for Base (where there already is a spinlock for when all uses should spin).

**Comment by vchuravy** [comment]
Yeah @jpsamaroo is running into this with trying to make Distributed.jl thread-safe, but maybe we can use `Spinlock`s there.

**Pull request merged**
