### PR TITLE
Generalize Sparse Array Indices Type in Struct Def

### PR DESCRIPTION
**Pull request by Roger-luo**
This PR generalize the struct defines of sparse arrays to be able to use general indices type, and I let the default `Ti` to be `Cint` so that this change doesn't change the old behaviour. So I think the current tests should cover this PR.

I'll submit another PR to change the conversion logic between CPU sparse array and the CUDA sparse array.

### CODE REVIEW

**Comment by Roger-luo** [comment]
looks like something went wrong in `GPUArrays`? I tried to run the failed tests locally, but they seems to pass.

**Comment by maleadt** [comment]
Yeah, there were some issues with the master branch, so I was/am holding off on merging new PRs until I got that figured out. Getting close now, so if you rebase this PR it should at least pass CI already.

**Review by kshyatt — APPROVED** [review]
LGTM assuming tests pass. Might be nice to include a note in the docs somewhere explaining that `Cint` is the "preferred" type but others are supported?

**Comment by Roger-luo** [comment]
> Might be nice to include a note in the docs somewhere explaining that Cint is the "preferred" type but others are supported?

Sure, but `Int64` is not supported yet... I'm planning to actually support `Int64` by dispatching on the algorithm 2 (or algorithm 3, we can discuss this later) of `SpMM` but haven't done this yet. I'll do this in a seperate PR since I'm not sure what algorithm to choose and what the dispatch behaviour should be

**Pull request merged**
