### PR TITLE
specialize +/- op for sparse diag

### LINKED ISSUE #1469: CUSPARSE: Diagonal + CSC/CSR gives dense array
I'm not sure if this is a bug or enhancement, but I think this should be a bug... so currently if you add a sparse matrix with a diagonal the broadcast will think their result is dense. e.g

<details>

```julia
julia> sprand(10, 10, 0.1) + Diagonal(rand(10))
10×10 SparseMatrixCSC{Float64, Int64} with 17 stored entries:
 0.231037   ⋅        …   ⋅         ⋅ 
 0.172736  0.362504      ⋅         ⋅ 
  ⋅         ⋅            ⋅         ⋅ 
  ⋅         ⋅           0.400551   ⋅ 
  ⋅         ⋅           0.13433    ⋅ 
  ⋅         ⋅        …   ⋅         ⋅ 
  ⋅         ⋅            ⋅         ⋅ 
  ⋅         ⋅            ⋅         ⋅ 
  ⋅         ⋅           0.362257   ⋅ 
  ⋅         ⋅            ⋅        0.545874

julia> cu(sprand(10, 10, 0.1)) + cu(Diagonal(rand(10)))
10×10 CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}:
 0.948874  0.0       …  0.0      0.0
 0.0       0.149517     0.0      0.0
 0.0       0.0          0.0      0.0
 0.0       0.0          0.0      0.0
 0.0       0.0          0.0      0.0
 0.0       0.0       …  0.0      0.146771
 0.0       0.0          0.0      0.0
 0.0       0.0          0.0      0.0
 0.486828  0.0          1.58939  0.468612
 0.0       0.0          0.0      0.832776
```

</details>

I guess this might due to some misconfig of the broadcast implementation on inferring the sparse structure. In `SparseArrays`, it seems to be handled by a specific broadcast style at this line
https://github.com/JuliaSparse/SparseArrays.jl/blob/main/src/higherorderfns.jl#L78

I'm not sure what would be the right way to do it with `CuSparseMatrix` types however

### PR DESCRIPTION
**Pull request by Roger-luo**
I just move the patch we had for [Bloqade](https://github.com/QuEraComputing/Bloqade.jl/blob/master/lib/BloqadeCUDA/src/patch.jl) to this PR to fix #1469 

It's not really a fix but more a workaround tho, since we don't actually have the general mechanism

### CODE REVIEW

**Comment by Roger-luo** [comment]
@maleadt bump

**Comment by Roger-luo** [comment]
Any chance to have a review of this? @maleadt  I think I did what was done for the other operator. Would be nice that I can let my users use the master branch of CUDA instead of my fork at least...

**Comment by maleadt** [comment]
Sorry for the delay. I'm not really a fan of these specializations, as such an approach doesn't scale. I think it would be better to do this by selecting a compatible broadcaststyle as mentionedn in https://github.com/JuliaGPU/CUDA.jl/issues/1469. Did you try that?

**Comment by Roger-luo** [comment]
you mean directly subtyping the `SparseMatStyle` type? yeah that could work I haven't tried

**Comment by maleadt** [comment]
No, I meant that it would be better to automatically promote the diagonal arguments automatically to sparse inputs, like Base does with PromoteToSparse. Otherwise we're limited to the exact support of `+` and `-` being added here, and other operators (that are implemented in Base but still use broadcast) wouldn't work.

**Comment by Roger-luo** [comment]
I just had a brief look at the `PromoteToSparse` implementation, I don't fully understand the `copy(::Broadcasted{PromoteToSparse})` implementation it seems to involve a few customs for loops/map functions (e.g https://github.com/JuliaSparse/SparseArrays.jl/blob/main/src/higherorderfns.jl#L462) which has some overlapping with what exists in https://github.com/JuliaGPU/CUDA.jl/blob/master/lib/cusparse/broadcast.jl#L537 it doesn't seem to work for me by just switching broadcast style.

This would take some more time to finish, but as there are already specializations, would it be possible to merge this PR first so that at least the ODE solvers work? then we can come back and generalize the implementation by implementing the kernel for those map functions.

**Comment by maleadt** [comment]
> This would take some more time to finish, but as there are already specializations, would it be possible to merge this PR first so that at least the ODE solvers work? then we can come back and generalize the implementation by implementing the kernel for those map functions.

Yeah OK.

**Pull request merged**
