### PR TITLE
Update wrappers for CUDA v12.6.1

### PR DESCRIPTION
**Pull request by amontoison**

### CODE REVIEW

**Comment by maleadt** [comment]
Huh, I didn't expect header changes in a patch update.

**Comment by maleadt** [comment]
https://github.com/JuliaGPU/CUDA.jl/pull/2461#issuecomment-2272944004

**Comment by amontoison** [comment]
https://github.com/JuliaGPU/CUDA.jl/blob/cab8f2d103c9eab9ac8e18660964715f641fcd52/lib/complex.jl#L1
Documentation of the routine [here](https://docs.nvidia.com/cuda/cuquantum/latest/custatevec/api/functions.html?highlight=custateveccomputeexpectationbatched#custateveccomputeexpectationbatched).
I will update the toml file.

**Comment by maleadt** [comment]
> # CUDA's complex types are defined in terms of vector types (float2, double2),

I know, but our wrapper generator doesn't emit such code. The fact that I had to manually edit is what I was hinting at.

Anyway, LGTM, CUDNN failure unrelated. Thanks for the PR!

**Pull request merged**
