### PR TITLE
Enzyme: allocation functions

### PR DESCRIPTION
**Pull request by wsmoses**

### CODE REVIEW

**Comment by wsmoses** [comment]
@maleadt the 1.8 failure seems unrelated (and 1.9/1.10 seem to pass).

Mind giving it a review (and if all is well potentially backport)

**Comment by wsmoses** [comment]
@vchuravy @maleadt mind leaving a review?

**Comment by vchuravy** [comment]
The downstream Enzyme test seems to be failing?

**Comment by wsmoses** [comment]
@vchuravy this seems to be the same issue from [earlier](https://github.com/EnzymeAD/Enzyme.jl/issues/1442):

"_bk;t=1715973520023  LLVM error: Failed to materialize symbols: { (JuliaExternal, { libname_cuCtxGetApiVersion_44851, libname_cuMemAlloc_v2_45055, libname_cuCtxGetCurrent_44116, libname_cuDeviceGetName_44551, libname_cuCtxSetCurrent_44077, libname_cuCtxGetDevice_45018, libname_cuCtxPushCurrent_v2_45012, libname_cuStreamQuery_45023, libname_cuMemPoolCreate_44209, libname_cuCtxGetId_44849, libname_cuMemAllocFromPoolAsync_45053, libname_cuCtxSynchronize_44886, libname_cuCtxGetCurrent_44075, libname_cuCtxSynchronize_44880, augmented_julia_alloc_43860wrap, libname_cuMemAllocAsync_45045, libname_cudaRuntimeGetVersion_44545, libname_cuDeviceGetCount_44033, libname_cuMemAlloc_v2_45047, libname_cuDeviceSetMemPool_44203, libname_cuStreamCreate_44402, libname_cuStreamQuery_45024, libname_cuMemPoolTrimTo_44874, libname_cuCtxGetId_44124, libname_cuDeviceGetAttribute_44374, libname_cuStreamSynchronize_45077, libname_cuMemGetInfo_v2_44312, libname_cuMemPoolCreate_44110, libname_cuDeviceGet_44822, libname_cuMemPoolSetAttribute_44198, libname_cuStreamSynchronize_45072, libname_cuDevicePrimaryCtxRetain_44435, libname_cuMemPoolGetAttribute_44067, diffejulia_alloc_43860wrap, libname_cuCtxSetCurrent_44836, libname_cuCtxPopCurrent_v2_45015 }) }
"

**Comment by maleadt** [comment]
@vchuravy Feel free to merge when tests pass.

**Comment by wsmoses** [comment]
@vchuravy @maleadt ah finally it passes. I'll make a backports PR as well

**Pull request merged**
