### PR TITLE
CUBLAS: nrm2 support Int64 array length

### PR DESCRIPTION
**Pull request by tipfom**
This PR adds functionality concerning issue #2268 .

### CODE REVIEW

**Comment by maleadt** [comment]
I wonder if we should just switch as much as possible to the 64-bit interface. Reading https://developer.nvidia.com/blog/new-cublas-12-0-features-and-matrix-multiplication-performance-on-nvidia-hopper-gpus/:

> Performance is the main focus for cuBLAS, so when the arguments passed to 64-bit integer API fit into the 32-bit range, the library uses the same kernels as if the user calls 32-bit integer API.

Only on CUDA 12, of course.

**Comment by tipfom** [comment]
That would also be an option, but I'm not qualified to comment on how much effort that would be. I've encountered the nrm2 problem when working with the cuStateVector library, which supports arrays with more than 2^32 elements on A100 GPUs

**Comment by amontoison** [comment]
> I wonder if we should just switch as much as possible to the 64-bit interface. Reading https://developer.nvidia.com/blog/new-cublas-12-0-features-and-matrix-multiplication-performance-on-nvidia-hopper-gpus/:
> 
> > Performance is the main focus for cuBLAS, so when the arguments passed to 64-bit integer API fit into the 32-bit range, the library uses the same kernels as if the user calls 32-bit integer API.
> 
> Only on CUDA 12, of course.

Approved, we should update our Julia interface to use the ILP64 API.
I will open a PR.

**Comment by maleadt** [comment]
Superseded by https://github.com/JuliaGPU/CUDA.jl/pull/2270

**Pull request closed without merging**
