### PR TITLE
Enhance warning under a profiler

### PR DESCRIPTION
**Pull request by huiyuxie**
Fix my minor issue #2540.

### CODE REVIEW

**Comment by huiyuxie** [comment]
https://github.com/JuliaGPU/CUDA.jl/blob/a085bbb3d7856dfa929e6cdae04a146a259a2044/src/initialization.jl#L213-L215
I'm curious about one thing here - we can’t simply remove `nvperf` here to eliminate the warning as we rely on it for basic internal profiling like `CUDA.@profile` https://cuda.juliagpu.org/stable/development/profiling/#Integrated-profiler?

And is it possible to remove this warning entirely when using a profiler? (Just curious; I have no strong opinion on how to deal with this issue.)

**Comment by maleadt** [comment]
I'm not sure what you're asking. Any library picked up from the system is generally bad news, since we aim to provide everything through artifacts. The only exception is when profiling, in which case NVIDIA tools will preload libraries.

**Comment by huiyuxie** [comment]
Thanks for your reply 👍- I aimed to confirm that there isn’t a better way (i.e., removing the warning completely when under a profiler) to handle this issue.

Please review

**Comment by huiyuxie** [comment]
Review please thanks @maleadt

**Comment by maleadt** [comment]
Thanks!

**Pull request merged**
