### PR TITLE
Implement and improve reclaim for the stream-ordered allocator

### LINKED ISSUE #952: Reclaim with stream-ordered allocator
It should probably call `trim(memory_pool(device()))`

Also verify that this makes the background reclaim job work again.

### PR DESCRIPTION
**Pull request by maleadt**
Fixes https://github.com/JuliaGPU/CUDA.jl/issues/952

cc @marius311, you asked for this IIRC. This also changes the order of things when reclaiming memory, and might improve performance close to OOM. Could you test this?

### CODE REVIEW

**Comment by marius311** [comment]
Getting a `UndefVarError: @typed_ccall not defined` trying to precompile CUDA with this PR, do I need anything else on PRs / maser to test this?

**Comment by maleadt** [comment]
Yes, check the Manifest (you can just use it to check which additional dependencies you need to install from specific branches). Currently, that's LLVM#master.

**Comment by marius311** [comment]
Ok, tried it out, I don't know if this is very helpful but overall I don't really see any performance difference between 3.3.0 and this PR when I have `JULIA_CUDA_MEMORY_POOL=none`, however both are much worse than `JULIA_CUDA_MEMORY_POOL=binned` Some initial microbencharks I had done made me think the stream-ordered allocator was doing better, but on the real problem its decidedly worse unfortunately. it also causes wierd looking usage/memory behavior e.g.

image

I don't see this without it, and this is otherwise a pretty unchanging for-loop, so the drastic change isnt explained by what my code is doing per se. In any case, once whatever this is is sorted out, will be nice to be able to reclaim memory, so from that point of view this PR makes sense.

**Comment by maleadt** [comment]
> `JULIA_CUDA_MEMORY_POOL=none`

That disables the stream-ordered memory allocator.

**Comment by marius311** [comment]
Ah oops, I had misunderstood that. Rereading, I suppose to use the stream ordered allocator I should just not set that variable at all, rather than set it to none? (in addition to using CUDA 11.2+)

**Comment by maleadt** [comment]
Correct. You can force it with `JULIA_CUDA_MEMORY_POOL=cuda`, but that should be unnecessary.

**Comment by maleadt** [comment]
WMMA test failure fixed in https://github.com/JuliaGPU/CUDA.jl/pull/985.

**Pull request merged**
