### PR TITLE
Upgrade CUTENSORNET to v1.1

### PR DESCRIPTION
**Pull request by maleadt**
This is the part from https://github.com/JuliaGPU/CUDA.jl/pull/1623 that fails CI, rebased on top of all recent changes (submodule split, JLL conversion), so should be easier for @kshyatt to take a look at :-)

This also adds logging, so run with `JULIA_DEBUG=CUTENSORNET` for more information.

### CODE REVIEW

**Comment by kshyatt** [comment]
Do we need some kind of version bounds on `CUTENSOR` in `Project.toml`?

**Comment by maleadt** [comment]
Nope, only on the JLL, and the cuQuantum 22.7 JLL has a bound on CUTENSOR_JLL.

**Comment by kshyatt** [comment]
OK, got this running on newer CUTENSOR and the tests are busted. I'll try to fix ASAP :)

**Comment by maleadt** [comment]
Let's re-enable CI.

**Comment by kshyatt** [comment]
Added a new test dep on `TensorOperations` for correctness testing.

**Comment by kshyatt** [comment]
@maleadt good to go? is the new test dep ok?

**Comment by maleadt** [comment]
Yeah, looks great, thanks!

**Pull request merged**
