### PR TITLE
Issue #2533: Preserving the buffer type in linear algebra

### PR DESCRIPTION
**Pull request by kmp5VT**
An attempt to fix buffer type linear algebra issue. It looks like the `CuArray` function is called many times and there is no book keeping of the `memory_type`. I manually added to the `CuArray` function calls. One could also make this part of the function call. See Issue #2533

### CODE REVIEW

**Comment by maleadt** [comment]
Thanks for the PR! It is often easier to use the `similar` function, which can take an `eltype` and `dims`:

>  `similar(array, [element_type=eltype(array)], [dims=size(array)])`
>
>  Create an uninitialized mutable array with the given element type and size, based upon the given source array. The second and third arguments are both optional, defaulting to the given array's eltype and size.
>  The dimensions may be specified either as a single tuple argument or as a series of integer arguments.

**Comment by kmp5VT** [comment]
@maleadt Oh yes, similar is a better way to go. I will update these changes with similar, thanks!

**Comment by maleadt** [comment]
Yeah looks better with `similar` 🙂 The `memory_type` now can go, though?

**Comment by maleadt** [comment]
LGTM, CI failure unrelated.

Why the partial revert though?

**Comment by kmp5VT** [comment]
@maleadt I wasn't sure what the failures were related to. With the changes I reverted, I haven't yet had time to verify that they work as expected so I wasn't sure if those changes were causing the check failures. I have more time today and can check that function and re-push the changes.

**Comment by kmp5VT** [comment]
@maleadt I was able to check that the gebrd! code does work properly if all the tensors are on unified memory. I added back those changes. Thanks!

**Comment by maleadt** [comment]
Thanks!

**Pull request merged**
