### PR TITLE
Update to CUDA 11.8

### PR DESCRIPTION
**Pull request by maleadt**
@amontoison Locally I'm seeing a bunch of:

```
Error in testset cusparse/generic:
Error During Test at /home/tim/Julia/pkg/CUDA/test/cusparse/generic.jl:107
  Got exception outside of a @test
  UndefVarError: tril not defined
  Stacktrace:
    [1] macro expansion
      @ ~/Julia/pkg/CUDA/test/cusparse/generic.jl:117 [inlined]
    [2] macro expansion
      @ ~/Julia/depot/juliaup/julia-1.8.2+0.x64/share/julia/stdlib/v1.8/Test/src/Test.jl:1433 [inlined]
    [3] macro expansion
      @ ~/Julia/pkg/CUDA/test/cusparse/generic.jl:107 [inlined]
    [4] macro expansion
      @ ~/Julia/depot/juliaup/julia-1.8.2+0.x64/share/julia/stdlib/v1.8/Test/src/Test.jl:1433 [inlined]
    [5] top-level scope
      @ ~/Julia/pkg/CUDA/test/cusparse/generic.jl:106
    [6] include
      @ ./client.jl:476 [inlined]
    [7] #12
      @ ~/Julia/pkg/CUDA/test/runtests.jl:91 [inlined]
    [8] macro expansion
      @ ~/Julia/pkg/CUDA/test/setup.jl:55 [inlined]
    [9] macro expansion
      @ ~/Julia/depot/juliaup/julia-1.8.2+0.x64/share/julia/stdlib/v1.8/Test/src/Test.jl:1357 [inlined]
   [10] macro expansion
      @ ~/Julia/pkg/CUDA/test/setup.jl:55 [inlined]
   [11] macro expansion
      @ ~/Julia/pkg/CUDA/src/utilities.jl:25 [inlined]
   [12] macro expansion
      @ ~/Julia/pkg/CUDA/src/pool.jl:480 [inlined]
   [13] top-level scope
      @ ~/Julia/pkg/CUDA/test/setup.jl:54
   [14] eval
      @ ./boot.jl:368 [inlined]
   [15] runtests(f::Function, name::String, time_source::Symbol, snoop::Nothing)
      @ Main ~/Julia/pkg/CUDA/test/setup.jl:66
   [16] invokelatest(::Any, ::Any, ::Vararg{Any}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
      @ Base ./essentials.jl:729
   [17] invokelatest(::Any, ::Any, ::Vararg{Any})
      @ Base ./essentials.jl:726
   [18] (::Distributed.var"#110#112"{Distributed.CallMsg{:call_fetch}})()
      @ Distributed ~/Julia/depot/juliaup/julia-1.8.2+0.x64/share/julia/stdlib/v1.8/Distributed/src/process_messages.jl:285
   [19] run_work_thunk(thunk::Distributed.var"#110#112"{Distributed.CallMsg{:call_fetch}}, print_error::Bool)
      @ Distributed ~/Julia/depot/juliaup/julia-1.8.2+0.x64/share/julia/stdlib/v1.8/Distributed/src/process_messages.jl:70
   [20] macro expansion
      @ ~/Julia/depot/juliaup/julia-1.8.2+0.x64/share/julia/stdlib/v1.8/Distributed/src/process_messages.jl:285 [inlined]
   [21] (::Distributed.var"#109#111"{Distributed.CallMsg{:call_fetch}, Distributed.MsgHeader, Sockets.TCPSocket})()
      @ Distributed ./task.jl:484
Error in testset cusparse/generic:
Error During Test at /home/tim/Julia/pkg/CUDA/test/cusparse/generic.jl:136
  Got exception outside of a @test
  UndefVarError: tril not defined
  Stacktrace:
    [1] macro expansion
      @ ~/Julia/pkg/CUDA/test/cusparse/generic.jl:147 [inlined]
    [2] macro expansion
      @ ~/Julia/depot/juliaup/julia-1.8.2+0.x64/share/julia/stdlib/v1.8/Test/src/Test.jl:1433 [inlined]
    [3] macro expansion
      @ ~/Julia/pkg/CUDA/test/cusparse/generic.jl:136 [inlined]
    [4] macro expansion
      @ ~/Julia/depot/juliaup/julia-1.8.2+0.x64/share/julia/stdlib/v1.8/Test/src/Test.jl:1433 [inlined]
    [5] top-level scope
      @ ~/Julia/pkg/CUDA/test/cusparse/generic.jl:135
    [6] include
      @ ./client.jl:476 [inlined]
    [7] #12
      @ ~/Julia/pkg/CUDA/test/runtests.jl:91 [inlined]
    [8] macro expansion
      @ ~/Julia/pkg/CUDA/test/setup.jl:55 [inlined]
    [9] macro expansion
      @ ~/Julia/depot/juliaup/julia-1.8.2+0.x64/share/julia/stdlib/v1.8/Test/src/Test.jl:1357 [inlined]
   [10] macro expansion
      @ ~/Julia/pkg/CUDA/test/setup.jl:55 [inlined]
   [11] macro expansion
      @ ~/Julia/pkg/CUDA/src/utilities.jl:25 [inlined]
   [12] macro expansion
      @ ~/Julia/pkg/CUDA/src/pool.jl:480 [inlined]
   [13] top-level scope
      @ ~/Julia/pkg/CUDA/test/setup.jl:54
   [14] eval
      @ ./boot.jl:368 [inlined]
   [15] runtests(f::Function, name::String, time_source::Symbol, snoop::Nothing)
      @ Main ~/Julia/pkg/CUDA/test/setup.jl:66
   [16] invokelatest(::Any, ::Any, ::Vararg{Any}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
      @ Base ./essentials.jl:729
   [17] invokelatest(::Any, ::Any, ::Vararg{Any})
      @ Base ./essentials.jl:726
   [18] (::Distributed.var"#110#112"{Distributed.CallMsg{:call_fetch}})()
      @ Distributed ~/Julia/depot/juliaup/julia-1.8.2+0.x64/share/julia/stdlib/v1.8/Distributed/src/process_messages.jl:285
   [19] run_work_thunk(thunk::Distributed.var"#110#112"{Distributed.CallMsg{:call_fetch}}, print_error::Bool)
      @ Distributed ~/Julia/depot/juliaup/julia-1.8.2+0.x64/share/julia/stdlib/v1.8/Distributed/src/process_messages.jl:70
   [20] macro expansion
      @ ~/Julia/depot/juliaup/julia-1.8.2+0.x64/share/julia/stdlib/v1.8/Distributed/src/process_messages.jl:285 [inlined]
   [21] (::Distributed.var"#109#111"{Distributed.CallMsg{:call_fetch}, Distributed.MsgHeader, Sockets.TCPSocket})()
      @ Distributed ./task.jl:484
```

### CODE REVIEW

**Comment by amontoison** [comment]
`tril` is a function of `LinearAlgebra`. Can you add `using LinearAlgebra` at the top of `test/cusparse/generic.jl`?
It should fix the problem.

**Comment by maleadt** [comment]
> `tril` is a function of `LinearAlgebra`. Can you add `using LinearAlgebra` at the top of `test/cusparse/generic.jl`?

Yeah I realize that, and adding the import fixes the failure, but I'm suspicious why CI doesn't spot this...

**Comment by amontoison** [comment]
> > `tril` is a function of `LinearAlgebra`. Can you add `using LinearAlgebra` at the top of `test/cusparse/generic.jl`?
> 
> Yeah I realize that, and adding the import fixes the failure, but I'm suspicious why CI doesn't spot this...

I suppose that `test/cusparse.jl` is called before in the tests.

**Comment by maleadt** [comment]
> I suppose that `test/cusparse.jl` is called before in the tests.

Every test is called in its own module, so that shouldn't have any impact.

**Pull request merged**
