### PR TITLE
CUSPARSE: Support mixed type mv

### PR DESCRIPTION
**Pull request by Roger-luo**
from CUDA 11.0 the SpMV routine actually supports mixed normal/complex type https://docs.nvidia.com/cuda/cusparse/index.html#cusparse-generic-function-spmv This PR loose the type signature to allow such operation.

### CODE REVIEW

**Comment by Roger-luo** [comment]
hmm, somehow the CUDA 11.0 on CI doesn't support this routine, I'm not sure why on my AWS EC2 instance this works fine with CUDA 11.0, maybe I should just limit the version to CUDA 11.3+? What do you think? @maleadt

**Comment by maleadt** [comment]
Thanks for the PR.

> somehow the CUDA 11.0 on CI doesn't support this routine

Verify by checking the versioned documentation, https://developer.nvidia.com/cuda-toolkit-archive, and at the very least bound the tests, maybe also adding a warning or error at run time.

> I'm not sure why on my AWS EC2 instance this works fine with CUDA 11.0

Driver version != toolkit version. Are you using artifacts on that instance?

**Comment by Roger-luo** [comment]
I limited the test version to CUDA 11.3 which seems to be the first version supporting this feature, but I let the implementation to be generic which I think is fine since it would error when it hits the incompatible type.

**Comment by maleadt** [comment]
Test failures still related.

**Comment by maleadt** [comment]
Please don't use CI for development, we don't have enough resources for that. At the very least, mark PRs like that as draft, which will reduce the amount of jobs.

**Comment by Roger-luo** [comment]
sorry about that, do you know if there is a way to setup different CUDA versions locally? I'm not sure why it is still running the tests on the versions that I'm not specified. We just need to skip the tests in lower CUDA version in this PR.

**Comment by maleadt** [comment]
> do you know if there is a way to setup different CUDA versions locally

Yes, you set `JULIA_CUDA_VERSION` to e.g. `10.2`.

**Comment by Roger-luo** [comment]
hmmm @maleadt I might need some help for this issue, I tried to run the tests from 11.0 - 11.6 on my local machine by setting `JULIA_CUDA_VERSION` on a standard AWS EC2 `p3.2xlarge`. however all the tests passed on my machine, so I'm not sure why the CUSPARSE installed on the CI machine doesn't support mixed-type SpMV, which looks strange

**Comment by maleadt** [comment]
I think this issue was due to a change in 11.6.1, while our artifacts are 11.6.0. I've upgraded our artifacts since, and fixed that bug, so try rebasing (and in case a bug still manifests, you should be able to reproduce locally now).

Ref https://github.com/JuliaGPU/CUDA.jl/pull/1505, https://github.com/JuliaGPU/CUDA.jl/pull/1507, https://github.com/JuliaGPU/buildkite/commit/bd1a48018f2fbf67ce387c0f66d23058015fe778

**Comment by Roger-luo** [comment]
I think I fixed the tests now, how to trigger the tests again?

**Comment by maleadt** [comment]
Force push or close/reopen. I've restarted them through Buildkite now (but that requires an account).

**Pull request merged**
