### PR TITLE
remove some type-piracy from cusparse

### PR DESCRIPTION
**Pull request by vtjnash**
(There may be many more of these pirates here in these waters. I know of at least cusparse/device.jl also has an ndims stolen. Just trying to get the ball rolling in fixes here.)

### CODE REVIEW

**Comment by maleadt** [comment]
LGTM, thanks!

**Comment by vtjnash** [comment]
Could you look at fixing the other similar ones too? It seemed like SnoopCompile didn't report too many others

**Comment by maleadt** [comment]
https://github.com/JuliaGPU/CUDA.jl/pull/1878. Or are there other functions you're thinking about?

**Comment by vtjnash** [comment]
That is possibly all that I know of

**Pull request merged**
