### PR TITLE
Allow `PermutedDimsArray` in `gemm_strided_batched`

### PR DESCRIPTION
**Pull request by mcabbott**
This is copied from https://github.com/JuliaGPU/CuArrays.jl/pull/664, which needed https://github.com/FluxML/NNlib.jl/pull/191, now merged (but not yet tagged).

Summarising: 

CUBLAS's `gemm_strided_batched!` accepts strides apart from the ordered ones of a `CuArray`. This is potentially useful as it saves on performing `permutedims` before operations, and the obvious way to expose this is to let it accept `PermutedDimsArray`s. 

I presume that by the time anyone is calling `CuArrays.CUBLAS.gemm_strided_batched!`, they are well aware that the operation is to be done by CUBLAS, and not expecting dispatch to redirect to the CPU if it's an Array. So I changed this to accept any `AbstractArray`.

Then `NNlib.batched_mul` will be a friendly function which dispatches every kind of array to the best routine. I hope I got this sorted out! To perform e.g. matrix * 3-tensor contractions like [the table here](https://devblogs.nvidia.com/cublas-strided-batched-matrix-multiply/), the matrix should be reshaped to another 3-array, with a size=1 dimension to indicate no batch index, or batched matrix-vector, etc.

### CODE REVIEW

**Comment by maleadt** [comment]
> I presume that by the time anyone is calling `CuArrays.CUBLAS.gemm_strided_batched!`, they are well aware that the operation is to be done by CUBLAS, and not expecting dispatch to redirect to the CPU if it's an Array. So I changed this to accept any `AbstractArray`.

It serves as documentation too. Looking at the name of the function one could expect being able to use it with actual strided inputs (i.e. a non-contiguous view); which the `DenseCuArray` type specification prevents.

Please rebase on latest master to get CI.

**Comment by mcabbott** [comment]
It's a pity to lose the documentation aspect, but is there another way? Inserting some huge union isn't going to result in a readable `methods()`. Perhaps I could insert one more step to `_gemm_strided_batched!` with a wider signature, which the NNlib function calls? 

Can rebase but I think CI won't work until NNlib is tagged.

**Comment by maleadt** [comment]
> Can rebase but I think CI won't work until NNlib is tagged.

Oh, right. You can always add an explicit dep to the Manifest if you want to run CI before that happens.


> Perhaps I could insert one more step to `_gemm_strided_batched!` with a wider signature, which the NNlib function calls?

Eh, maybe just add a comment at the end of the line.
Does this actually test the PermuteDims case? Otherwise it might be easy to accidentally refactor this part of the changes away.

**Comment by mcabbott** [comment]
Good point about tests, I've added a few. 

And put NNlib#master in the manifest to test on CI. (Documentation still fails, I presume because it's on a different manifest.)

This needs something to make pointers, possibly just `Base.unsafe_convert(::Type{CuPtr{T}}, A::PermutedDimsArray) = ...`. Where should this live? I mean should Adapt or some other package somehow take care of this, instead of writing it directly?

**Comment by maleadt** [comment]
> This needs something to make pointers, possibly just `Base.unsafe_convert(::Type{CuPtr{T}}, A::PermutedDimsArray) = ...`. Where should this live? I mean should Adapt or some other package somehow take care of this, instead of writing it directly?

These conversions live in `array.jl`: https://github.com/JuliaGPU/CUDA.jl/blob/1139ffdcf77d5981357787dc69bf54bc62965c9e/src/array.jl#L370-L490. We used to have tthem for ReshapedArray and ReinterpretArray too, but recently we've switched back to implementing those with CuArray again.

**Comment by mcabbott** [comment]
Great, I've moved the pointer as you describe. 

NNlib is now tagged, and I adjusted the bound in Project.toml. But CI doesn't seem to see v0.7.7, perhaps it needs more time.

**Comment by maleadt** [comment]
Sometimes the PkgServer lags General a bit. I restarted the build, and there's a normal failure in the NNlib tests now.

**Comment by maleadt** [comment]
All green, let's merge this!

**Comment by mcabbott** [comment]
Thanks! And sorry about the excessive CI-ing, trying to finish this while away from my desktop maybe wasn't the brightest plan.

**Comment by maleadt** [comment]
No problem, that's what its there for. But it prompted me to add a smoke test that has to succeed before starting 10 other jobs :smile:

**Pull request merged**
