### PR TITLE
Use unchecked type conversions for `byte_perm` arguments

### LINKED ISSUE #1165: Calling `byte_perm` with `Int32` values inserts sign checks
I am calling `byte_perm` with `Int32` values. I find that the generated PTX code includes a check for the sign of the arguments, aborting if the arguments are negative. No such checks are introduced when using `UInt32` arguments.

I assume the problem is that `ccall` introduces a regular (checked) type conversion from `Int32` to `UInt32`.

It seems that many other intrinsics that accept `Int32` values on the Julia side, and which are passed as `UInt32` to `ccall`, will have the same problem.

### PR DESCRIPTION
**Pull request by eschnett**
Closes https://github.com/JuliaGPU/CUDA.jl/issues/1165

### CODE REVIEW

**Comment by maleadt** [comment]
Thanks. I agree we should think about how to generalize this to all intrinsics. The reason I didn't yet, is that it wasn't clear to me what to do with the return value here. If you invoke the intrinsic with UInt32's, you might not expect to get back an Int32 (or vice versa). But requiring `x` and `y` to be of the same type (in order to figure out the return type) seems like an arbitrary restriction too.

**Comment by eschnett** [comment]
The CUDA intrinsic returns `UInt32`. I would use the same return type in Julia, if that breaking change is an option. The semantics of signed and unsigned integers in Julia and CUDA are similar enough for this to make sense, and it's the least surprising.

The alternative, as you say, is to require the first two arguments to have the same signedness. I would be happy with this choice as well.

I would also allow all reasonable argument types (`[U]Int{8,16,32}`). I would in particular allow `UInt16` for the third argument, because writing `0x1234` is a very natural thing to do.

**Comment by maleadt** [comment]
> The CUDA intrinsic returns `UInt32`. I would use the same return type in Julia, if that breaking change is an option.

Yeah, that's definitely OK to do, these functions aren't widely used.

**Comment by maleadt** [comment]
Let's go ahead with the current implementation for now.

**Pull request merged**
