### PR TITLE
Add const keyword to type aliases declarations.

### PR DESCRIPTION
**Pull request by eliascarv**
I noticed that the type aliases were not declared with the const keyword and I decided to do this PR to add them.

### CODE REVIEW

**Comment by maleadt** [comment]
I thought that was only necessary back in the days?

**Comment by eliascarv** [comment]
Yes, but declaring it as a constant prevents the identifier from being assigned another value.
e. g.:
image

**Comment by eliascarv** [comment]
Also, non-constant global variables are not good for code performance.
e. g.:
image

**Comment by maleadt** [comment]
The performance improvement alone is reason enough to do it like that. Thanks for the PR!

**Pull request merged**
