### PR TITLE
Enzyme: support fill

### PR DESCRIPTION
**Pull request by wsmoses**

### CODE REVIEW

**Comment by wsmoses** [comment]
@vchuravy could this get a review, it's blocking some ML users

**Comment by maleadt** [comment]
Let's mark this as draft to save on CI resources until tests initially pass.

**Comment by wsmoses** [comment]
@maleadt okay I fixed the minor typos that hopefully should let it pass.

Assuming it passes, does it look good to you?

**Comment by maleadt** [comment]
> Assuming it passes, does it look good to you?

I'm unfamiliar with Enzyme, so I can't say much about the change.

The fact that it's very Enzyme specific (while using CUDA.jl-internals that are likely to break) actually makes me somewhat uncomfortable carrying this in CUDA.jl, even as a package extension, but as long as you and @vchuravy are happy to maintain it I guess it's fine to have (and test) this functionality...

**Comment by wsmoses** [comment]
yeah we commit to maintaining. And yeah that's why I think it makes most sense as an extension here (since it can follow cuda.jl internal changes correctly), since the enzymerules API is intentionally stable.

**Pull request merged**
