### PR TITLE
Use CUDA 11.2's stream-ordered allocator

### PR DESCRIPTION
**Pull request by maleadt**
The stream-ordered allocator consistently seems to allocate in under a us, while our caching allocator has a best-case allocation time of 300ns (but frequently takes much longer maintaining its pool structure). We might consider switching entirely to the stream-order allocator, for simplicity, but that needs benchmarking.

For now, this work is blocked on a CUDA bug where the default allocator gets corrupted by device resets. But even if managing our own memory pool, and dutifully creating a new one on device resets, I'm seeing spurious launch failures / segfaults when using the allocator (but synchronizing the stream after each alloc/free), and massive amounts of failures when using it truly asynchronous. So I think this'll have to wait until we hear back from NVIDIA.

### CODE REVIEW

**Comment by maleadt** [comment]
Sadly not fixed on 11.2 Update 1...

**Comment by maleadt** [comment]
This is too valuable to wait for NVIDIA to fix memory pools + device reset, so I decided to gimp `device_reset!` on CUDA 11.2 since nobody seems to be using that anyway. Thoughts, @vchuravy?

**Comment by vchuravy** [comment]
> This is too valuable to wait for NVIDIA to fix memory pools + device reset, so I decided to gimp `device_reset!` on CUDA 11.2 since nobody seems to be using that anyway.

That seems fair to me. We should add the warning to the documentation.

**Comment by maleadt** [comment]
```
      From worker 4:	========= CUDA-MEMCHECK

      From worker 4:	========= Internal Memcheck Warning: Detected use of unsupported CUDA memory pools. Please use the compute-sanitizer tool instead.

      From worker 4:	=========

      From worker 4:	========= Host API memory access error at host access to 0x302000200 of size 32 bytes

      From worker 4:	=========     Invalid start allocation on access by cudaMemcopy destination.
```

**Comment by algorithmx** [comment]
> ```
>       From worker 4:	========= CUDA-MEMCHECK
> 
>       From worker 4:	========= Internal Memcheck Warning: Detected use of unsupported CUDA memory pools. Please use the compute-sanitizer tool instead.
> 
>       From worker 4:	=========
> 
>       From worker 4:	========= Host API memory access error at host access to 0x302000200 of size 32 bytes
> 
>       From worker 4:	=========     Invalid start allocation on access by cudaMemcopy destination.
> ```

Hi Tim, 
could you please have a look at my post here?
https://discourse.julialang.org/t/cuda-memcheck-reports-over-1300-errors-with-4-lines-of-julia-code-with-cuda-jl/84516
https://discourse.julialang.org/t/cuda-jl-mystery-vscode-julia-extension-works-fine-but-commandline-run-fails/84524/5
It is perhaps related to this issue. I cannot make up a minimal reproduction of the error right now ...

**Comment by maleadt** [comment]
Please don't comment on old issues to gain attention, I would have responded when visiting Discourse.
You should use compute-sanitizer as the error states.

**Pull request merged**
