### PR TITLE
Update CUSPARSE for CUDA v12.0

### PR DESCRIPTION
**Pull request by amontoison**
@maleadt 
It should fix the issues of CUSPARSE with CUDA v"12.0".

### CODE REVIEW

**Comment by maleadt** [comment]
Awesome, thanks!

**Comment by maleadt** [comment]
I think this regressed the cusparse/broadcast tests, which only run on Julia 1.7+. I'll further hack the CI rules so that it tests that, on the other PR.

**Comment by maleadt** [comment]
OK yeah this definitely broke something, e.g., CPU CSC -> GPU CSR conversion:

```
julia> x = sprand(Float32, 2, 3, 0.5)
2×3 SparseMatrixCSC{Float32, Int64} with 3 stored entries:
  ⋅    ⋅       0.0217893
  ⋅   0.15284  0.269461

julia> CuSparseMatrixCSC(x)
2×3 CuSparseMatrixCSC{Float32, Int32} with 3 stored entries:
  ⋅    ⋅          0.021789312
  ⋅   0.15283984  0.26946056

julia> CuSparseMatrixCSR(x)
2×3 CuSparseMatrixCSR{Float32, Int32} with 3 stored entries:
  ⋅   0.15283984   ⋅
  ⋅    ⋅          0.26946056
```

**Comment by amontoison** [comment]
Hum :thinking: , the issue is related to a conversion GPU CSC -> GPU CSR but I dont understand why these tests passed: https://github.com/JuliaGPU/CUDA.jl/blob/master/test/cusparse/conversions.jl#L77-L101

**Comment by amontoison** [comment]
CUDA v"12.0":
```
julia> using CUDA, CUDA.CUSPARSE

julia> @testset "conversions between CuSparseMatrices" begin
           A = sprand(4, 4, 0.5)
           blockdim = 2
           for CuSparseMatrixType1 in (CuSparseMatrixCSC, CuSparseMatrixCSR, CuSparseMatrixCOO, CuSparseMatrixBSR)
               if CuSparseMatrixType1 == CuSparseMatrixBSR
                   dA1 = CuSparseMatrixType1(A, blockdim)
               else
                   dA1 = CuSparseMatrixType1(A)
               end
               @testset "conversion SparseMatrixCSC --> $CuSparseMatrixType1" begin
                   @test collect(dA1) ≈ A
               end
               for CuSparseMatrixType2 in (CuSparseMatrixCSC, CuSparseMatrixCSR, CuSparseMatrixCOO, CuSparseMatrixBSR)
                   CuSparseMatrixType1 == CuSparseMatrixType2 && continue
                   @testset "conversion $CuSparseMatrixType1 --> $CuSparseMatrixType2" begin
                       if CuSparseMatrixType2 == CuSparseMatrixBSR
                           dA2 = CuSparseMatrixType2(dA1, blockdim)
                       else
                           dA2 = CuSparseMatrixType2(dA1)
                       end
                       @test collect(dA1) ≈ collect(dA2)
                   end
               end
           end
       end

Test Summary:                                        | Pass  Fail  Total   Time
conversions between CuSparseMatrices                 |    7     9     16  21.5s
  conversion SparseMatrixCSC --> CuSparseMatrixCSC   |    1            1   0.8s
  conversion CuSparseMatrixCSC --> CuSparseMatrixCSR |          1      1  15.7s
  conversion CuSparseMatrixCSC --> CuSparseMatrixCOO |          1      1   3.7s
  conversion CuSparseMatrixCSC --> CuSparseMatrixBSR |          1      1   0.3s
  conversion SparseMatrixCSC --> CuSparseMatrixCSR   |          1      1   0.2s
  conversion CuSparseMatrixCSR --> CuSparseMatrixCSC |    1            1   0.0s
  conversion CuSparseMatrixCSR --> CuSparseMatrixCOO |    1            1   0.0s
  conversion CuSparseMatrixCSR --> CuSparseMatrixBSR |          1      1   0.0s
  conversion SparseMatrixCSC --> CuSparseMatrixCOO   |          1      1   0.0s
  conversion CuSparseMatrixCOO --> CuSparseMatrixCSC |          1      1   0.0s
  conversion CuSparseMatrixCOO --> CuSparseMatrixCSR |    1            1   0.0s
  conversion CuSparseMatrixCOO --> CuSparseMatrixBSR |          1      1   0.0s
  conversion SparseMatrixCSC --> CuSparseMatrixBSR   |          1      1   0.0s
  conversion CuSparseMatrixBSR --> CuSparseMatrixCSC |    1            1   0.0s
  conversion CuSparseMatrixBSR --> CuSparseMatrixCSR |    1            1   0.0s
  conversion CuSparseMatrixBSR --> CuSparseMatrixCOO |    1            1   0.0s
ERROR: Some tests did not pass: 7 passed, 9 failed, 0 errored, 0 broken.
```
CUDA v"11.8":
```
Test Summary:                        | Pass  Total   Time
conversions between CuSparseMatrices |   16     16  25.5s
Test.DefaultTestSet("conversions between CuSparseMatrices", Any[Test.DefaultTestSet("conversion SparseMatrixCSC --> CuSparseMatrixCSC", Any[], 1, false, false, true, 1.674819207754942e9, 1.674819208579218e9), Test.DefaultTestSet("conversion CuSparseMatrixCSC --> CuSparseMatrixCSR", Any[], 1, false, false, true, 1.674819208579279e9, 1.674819228588034e9), Test.DefaultTestSet("conversion CuSparseMatrixCSC --> CuSparseMatrixCOO", Any[], 1, false, false, true, 1.674819228588084e9, 1.674819232327371e9), Test.DefaultTestSet("conversion CuSparseMatrixCSC --> CuSparseMatrixBSR", Any[], 1, false, false, true, 1.674819232327439e9, 1.674819232628486e9), Test.DefaultTestSet("conversion SparseMatrixCSC --> CuSparseMatrixCSR", Any[], 1, false, false, true, 1.674819232633762e9, 1.674819232633989e9), Test.DefaultTestSet("conversion CuSparseMatrixCSR --> CuSparseMatrixCSC", Any[], 1, false, false, true, 1.674819232634001e9, 1.674819232636296e9), Test.DefaultTestSet("conversion CuSparseMatrixCSR --> CuSparseMatrixCOO", Any[], 1, false, false, true, 1.674819232636312e9, 1.674819232649402e9), Test.DefaultTestSet("conversion CuSparseMatrixCSR --> CuSparseMatrixBSR", Any[], 1, false, false, true, 1.674819232649429e9, 1.674819232652186e9), Test.DefaultTestSet("conversion SparseMatrixCSC --> CuSparseMatrixCOO", Any[], 1, false, false, true, 1.674819232657955e9, 1.674819232658419e9), Test.DefaultTestSet("conversion CuSparseMatrixCOO --> CuSparseMatrixCSC", Any[], 1, false, false, true, 1.674819232658432e9, 1.674819232670582e9), Test.DefaultTestSet("conversion CuSparseMatrixCOO --> CuSparseMatrixCSR", Any[], 1, false, false, true, 1.674819232670605e9, 1.674819232673305e9), Test.DefaultTestSet("conversion CuSparseMatrixCOO --> CuSparseMatrixBSR", Any[], 1, false, false, true, 1.67481923267332e9, 1.674819232678495e9), Test.DefaultTestSet("conversion SparseMatrixCSC --> CuSparseMatrixBSR", Any[], 1, false, false, true, 1.674819232684617e9, 1.67481923268485e9), Test.DefaultTestSet("conversion CuSparseMatrixBSR --> CuSparseMatrixCSC", Any[], 1, false, false, true, 1.674819232684861e9, 1.674819232689212e9), Test.DefaultTestSet("conversion CuSparseMatrixBSR --> CuSparseMatrixCSR", Any[], 1, false, false, true, 1.674819232689227e9, 1.674819232691556e9), Test.DefaultTestSet("conversion CuSparseMatrixBSR --> CuSparseMatrixCOO", Any[], 1, false, false, true, 1.674819232691572e9, 1.674819232695947e9)], 0, false, false, true, 1.674819207164252e9, 1.674819232695951e9)
```

**Comment by amontoison** [comment]
It seems that they broke something for conversions of **small** sparse matrices with the new release...
If the problem is in CUDA.jl, I don't see it.

**Pull request merged**
