### PR TITLE
Add `always_inline` kernel parameter

### PR DESCRIPTION
**Pull request by lcw**
Enable the forced inlining option from https://github.com/JuliaGPU/GPUCompiler.jl/pull/335.

### CODE REVIEW

**Comment by maleadt** [comment]
To move forward here, it would be interesting to extract the LLVM IR that fails to assemble, reduce it with e.g. creduce or llvm-reduce, and file an issue on the LLVM repo. Or maybe the reduced example would teach us something.

**Comment by maleadt** [comment]
Also, this doesn't strictly has to work everywhere. If it works OK for functions without atomics, that's fine, since it's a non-default option anyway.

**Comment by lcw** [comment]
Okay, I have changed the test to avoid atomics and it works on my local GPU now.  I don't have time to debug the atomic issue but for those interested the function that failed to inline was
```julia
 @eval f_expensive(x) = $(foldl((e, _) -> :(sink($e) + sink(x)), 1:100; init=:x))
```

**Comment by lcw** [comment]
Do I need to make the minimum version for GPUCompiler be 0.16.2 in `Project.toml`?

**Comment by maleadt** [comment]
> Do I need to make the minimum version for GPUCompiler be 0.16.2 in `Project.toml`?

Yes.

**Comment by lcw** [comment]
> > Do I need to make the minimum version for GPUCompiler be 0.16.2 in `Project.toml`?
> 
> Yes.

Done.  Please let me know if there is anything else you would like me to do before this gets merged.  Thanks!

**Pull request merged**
